<script>
  const words = [
    'Ocak|January',
    'Şubat|February',
    'Mart|March',
    'Nissan|April',
    'Mayis|May',
    'Haziran|June',
    'Temuz|July',
    'Ağustos|August',
    'Eylül|September',
    'Ekim|October',
    'Kasım|November',
    'Aralık|December',
    'İlkbahar|Spring',
    'Yaz|Summer',
    'Sonbahar|Fall',
    'Kış|Winter',
  
    'gelmek|to come',
    'gitmek|to go',
    'yapmak|to do',
    'yemek|to eat',
    'içmek|to drink',
    'konuşmak|to speak',
    'anlamak|to understand',
    'okumak|to read',
    'yazmak|to write',
    'dinlemek|to listen',
    'izlemek|to watch',
    'çalışmak|to work',
    'öğrenmek|to learn',
    'öğretmek|to teach',
    'almak|to take',
    'vermek|to give',
    'sevmek|to love',
    'istemek|to want',
    'bulmak|to find',
    'koymak|to put',
    'söylemek|to say',
    'çağırmak|to call',
    'görmek|to see',
    'duymak|to hear',
    'koklamak|to smell',
    'tatmak|to taste',
    'dokunmak|to touch',
    'kapatmak|to close',
    'açmak|to open',
    'beklemek|to wait',
    'koşmak|to run',
    'yürümek|to walk',
    'oturmak|to sit',
    'kalkmak|to stand up',
    'düşmek|to fall',
    'uyumak|to sleep',
    'uyanmak|to wake up',
    'gülmek|to laugh',
    'ağlamak|to cry',
    'bilmek|to know',
    'anlatmak|to explain',
    'gezmek|to travel',
    'yaşamak|to live',
    'ölmek|to die',
    'kazanmak|to win',
    'kaybetmek|to lose',
    'hatırlamak|to remember',
    'unutmak|to forget',
    'korkmak|to fear',
    'sevinmek|to be happy',
    'üzülmek|to be sad',
    'başlamak|to start',
    'bitirmek|to finish',
    'çizmek|to draw',
    'boyamak|to paint',
    'yüzmek|to swim',
    'atlamak|to jump',
    'kavga etmek|to fight',
    'sarılmak|to hug',
    'öpüşmek|to kiss',
    'tanışmak|to meet',
    'karşılamak|to welcome',
    'uğurlamak|to send off',
    'görüşmek|to see each other',
    'yardım etmek|to help',
    'terk etmek|to leave',
    'dönmek|to return',
    'alışveriş yapmak|to shop',
    'dolaşmak|to wander',
    'denemek|to try',
    'tekrar etmek|to repeat',
    'sormak|to ask',
    'cevaplamak|to answer',
    'taşımak|to carry',
    'göndermek|to send',
    'kullanmak|to use',
    'sürmek|to drive',
    'uçmak|to fly',
    'yıkamak|to wash',
    'temizlemek|to clean',
    'yapıştırmak|to stick',
    'çıkarmak|to remove',
    'çözmek|to solve',
    'geçmek|to pass',
    'kalmak|to stay',
    'ağrımak|to hurt',
    'oynamak|to play',
    'düşünmek|to think',
    'saymak|to count',
    'işaret etmek|to point',
    'ihtiyaç duymak|to need',
    'hissetmek|to feel',
    'yakalamak|to catch',
    'bırakmak|to let go',
    'çekmek|to pull',
    'itmek|to push',
    'dönmek|to turn',
    'ayrılmak|to separate',
    'birleştirmek|to unite',
    'dolaşmak|to stroll',
    'alışmak|to get used to',
    'kabul etmek|to accept',
    'reddetmek|to refuse',
    'takip etmek|to follow',
    'saklamak|to hide',
    'bulunmak|to be located',
    'katılmak|to join',
    'tartışmak|to discuss',
    'paylaşmak|to share',
    'izah etmek|to explain',
    'karar vermek|to decide',
    'korkutmak|to scare',
    'sakinleşmek|to calm down',
    'tavsiye etmek|to recommend',
    'davet etmek|to invite',
    'anlatmak|to tell',
    'sürdürmek|to continue',
    'boşaltmak|to empty',
    'doldurmak|to fill',
    'yakmak|to light',
    'söndürmek|to extinguish',
    'seçmek|to choose',
    'tahmin etmek|to guess',
    'olmak|to be',
    'var olmak|to exist',
    'ihtiyaç duymak|to require',
    'inanmak|to believe',
    'teşekkür etmek|to thank',
    'dilemek|to wish',
    'umut etmek|to hope',
    'başarmak|to achieve',
    'ilgi göstermek|to show interest',
    'övmek|to praise',
    'eleştirmek|to criticize',
    'çalışmak|to study',
    'denemek|to attempt',
    'anlamak|to comprehend',
    'kesmek|to cut',
    'pişirmek|to cook',
    'ısıtmak|to heat',
    'soğutmak|to cool',
    'eklemek|to add',
    'çıkarmak|to subtract',
    'çarpma yapmak|to multiply',
    'bölmek|to divide',
    'beklemek|to expect',
    'aramak|to search',
    'bulmak|to find',
    'satın almak|to buy',
    'satmak|to sell',
    'istemek|to request',
    'emretmek|to command',
    'emir vermek|to order',
    'şarkı söylemek|to sing',
    'dans etmek|to dance',
    'bahsetmek|to mention',
    'davranmak|to behave',
    'affetmek|to forgive',
    'bağışlamak|to pardon',
    'iyileşmek|to recover',
    'iyileştirmek|to heal',
    'öğretmek|to educate',
    'egzersiz yapmak|to exercise',
    'çalıştırmak|to operate',
    'uygulamak|to apply',
    'tecrübeli olmak|to experience',
    'katılmak|to attend',
    'katılmak|to participate',
    'kaçmak|to escape',
    'yakalamak|to capture',
    'hüküm vermek|to judge',
    'zorlamak|to force',
    'etkilemek|to affect',
    'araştırmak|to research',
    'incelemek|to examine',
    'keşfetmek|to discover',
    'araştırmak|to investigate',
    'taramak|to scan',
    'taramak|to browse',
    'teşhis etmek|to diagnose',
    'tekrar etmek|to reiterate',
    'sınav yapmak|to test',
    'denetlemek|to supervise',
    'gözetlemek|to observe',
    'incelemek|to inspect',
    'analiz etmek|to analyze',
    'özetlemek|to summarize',
    'yorumlamak|to interpret',
    'karşılaştırmak|to compare',
    'ele almak|to handle',
    'yönetmek|to manage',
    'işletmek|to operate',
    'tanımlamak|to define',
    'tasvir etmek|to describe',
    'anlamak|to perceive',
    'gözden geçirmek|to review',
    'sonuçlandırmak|to conclude',
    'incelemek|to scrutinize',
    
    'araba|car',
    'ev|house',
    'okul|school',
    'masa|table',
    'sandalye|chair',
    'kitap|book',
    'defter|notebook',
    'kalem|pen',
    'bilgisayar|computer',
    'telefon|phone',
    'bahçe|garden',
    'şehir|city',
    'köy|village',
    'sokak|street',
    'park|park',
    'dağ|mountain',
    'deniz|sea',
    'göl|lake',
    'nehir|river',
    'orman|forest',
    'çöl|desert',
    'hava|air',
    'su|water',
    'ateş|fire',
    'toprak|soil',
    'ağaç|tree',
    'çiçek|flower',
    'yaprak|leaf',
    'meyve|fruit',
    'sebze|vegetable',
    'elma|apple',
    'armut|pear',
    'muz|banana',
    'portakal|orange',
    'üzüm|grape',
    'çilek|strawberry',
    'karpuz|watermelon',
    'kavun|melon',
    'domates|tomato',
    'salatalık|cucumber',
    'biber|pepper',
    'patates|potato',
    'havuç|carrot',
    'soğan|onion',
    'sarımsak|garlic',
    'ekmek|bread',
    'süt|milk',
    'peynir|cheese',
    'yoğurt|yogurt',
    'et|meat',
    'balık|fish',
    'tavuk|chicken',
    'yumurta|egg',
    'pirinç|rice',
    'makarna|pasta',
    'çorba|soup',
    'salata|salad',
    'kahve|coffee',
    'çay|tea',
    'şeker|sugar',
    'tuz|salt',
    'biber|pepper',
    'yağ|oil',
    'tereyağı|butter',
    'bal|honey',
    'reçel|jam',
    'çikolata|chocolate',
    'dondurma|ice cream',
    'tatlı|dessert',
    'pasta|cake',
    'kurabiye|cookie',
    'bisküvi|biscuit',
    'meyve suyu|fruit juice',
    'gazoz|soda',
    'su|water',
    'bardak|glass',
    'şişe|bottle',
    'kupa|cup',
    'tabak|plate',
    'çatal|fork',
    'kaşık|spoon',
    'bıçak|knife',
    'tepsi|tray',
    'tencere|pot',
    'tava|pan',
    'kap|container',
    'çamaşır makinesi|washing machine',
    'bulaşık makinesi|dishwasher',
    'buzdolabı|refrigerator',
    'fırın|oven',
    'mikrodalga|microwave',
    'klima|air conditioner',
    'ısıtıcı|heater',
    'elektrik|electricity',
    'şarj aleti|charger',
    'pil|battery',
    'kablo|cable',
    'lamba|lamp',
    'ampul|bulb',
    'televizyon|television',
    'radyo|radio',
    'hoparlör|speaker',
    'kulaklık|headphones',
    'kamera|camera',
    'fotoğraf makinesi|photo camera',
    'video kamera|video camera',
    'saat|clock',
    'takvim|calendar',
    'harita|map',
    'ayna|mirror',
    'kapı|door',
    'pencere|window',
    'perde|curtain',
    'halı|carpet',
    'yatak|bed',
    'yastık|pillow',
    'battaniye|blanket',
    'dolap|wardrobe',
    'çekmece|drawer',
    'raf|shelf',
    'kanepe|sofa',
    'koltuk|armchair',
    'tuvalet|toilet',
    'banyo|bathroom',
    'duş|shower',
    'küvet|bathtub',
    'lavabo|sink',
    'sabun|soap',
    'havlu|towel',
    'diş fırçası|toothbrush',
    'diş macunu|toothpaste',
    'tıraş bıçağı|razor',
    'şampuan|shampoo',
    'saç kremi|conditioner',
    'saç kurutma makinesi|hair dryer',
    'fırça|brush',
    'tarak|comb',
    'makyaj|makeup',
    'parfüm|perfume',
    'deodorant|deodorant',
    'aile|family',
    'anne|mother',
    'baba|father',
    'kardeş|sibling',
    'abi|older brother',
    'abla|older sister',
    'erkek kardeş|brother',
    'kız kardeş|sister',
    'çocuk|child',
    'bebek|baby',
    'arkadaş|friend',
    'dost|close friend',
    'komşu|neighbor',
    'öğrenci|student',
    'öğretmen|teacher',
    'doktor|doctor',
    'hemşire|nurse',
    'mühendis|engineer',
    'mimar|architect',
    'işçi|worker',
    'çiftçi|farmer',
    'polis|police officer',
    'asker|soldier',
    'avukat|lawyer',
    'hakim|judge',
    'şoför|driver',
    'pilot|pilot',
    'kaptan|captain',
    'garson|waiter',
    'aşçı|chef',
    'temizlikçi|cleaner',
    'bahçıvan|gardener',
    'tesisatçı|plumber',
    'elektrikçi|electrician',
    'kuaför|hairdresser',
    'terzi|tailor',
    'satıcı|seller',
    'müşteri|customer',
    'yazar|writer',
    'şair|poet',
    'sanatçı|artist',
    'müzisyen|musician',
    'şarkıcı|singer',
    'dansçı|dancer',
    'oyuncu|actor',
    'yönetmen|director',
    'prodüktör|producer'
  ].map(word => word.split('|'))
  
  function shuffle(array) {
    let currentIndex = array.length, randomIndex;
  
    // While there remain elements to shuffle...
    while (currentIndex != 0) {
  
      // Pick a remaining element...
      randomIndex = Math.floor(Math.random() * currentIndex);
      currentIndex--;
  
      // And swap it with the current element.
      [array[currentIndex], array[randomIndex]] = [
        array[randomIndex], array[currentIndex]];
    }
  
    return array;
  }
  
  let currentWords = shuffle(words);
  let index = 0;
  let turkish = false;
  let currentWord;
  let flip = false;
  next();
      
  function next() {
    index++;
    if (index >= words.length) {
      index = 0;
      currentWords = shuffle(words);
    } else {
      turkish = Math.random() > 0.5;
    }
    currentWord = currentWords[index]
  }
  
  function keydown(e) {
    if (!flip) {
      turkish = !turkish;
      flip = true;
    } else {
      flip = false;
      next();
    }
  }
  </script>
  
  <svelte:window on:keydown={keydown} on:pointerdown={keydown} />
  
  <div>
    {currentWord[turkish ? 0 : 1]}
  </div>
  
  <style>
    :global(body) {
      padding: 0;
      margin: 0;
    }
    div {
      user-select: none;
      position: absolute;
      text-align: center;
      width: 100%;
      top: 50%;
      transform: translateY(-50%);
      font-size: 56px;
    }
  </style>