/**
 * Single source of truth for Turkish–English vocabulary.
 * Used by web app (via Vite alias) and by scripts (direct import).
 * @type {{ tr: string, en: string }[]}
 */
export const words = [
	{ tr: 'merhaba', en: 'hello' },
	{ tr: 'evet', en: 'yes' },
	{ tr: 'hayır', en: 'no' },
	{ tr: 'teşekkürler', en: 'thank you' },
	{ tr: 'lütfen', en: 'please' },
	{ tr: 'tamam', en: 'okay' },
	{ tr: 'iyi', en: 'good' },
	{ tr: 'kötü', en: 'bad' },
	{ tr: 'güzel', en: 'beautiful' },
	{ tr: 'büyük', en: 'big' },
	{ tr: 'küçük', en: 'small' },
	{ tr: 'yeni', en: 'new' },
	{ tr: 'eski', en: 'old' },
	{ tr: 'çok', en: 'very' },
	{ tr: 'biraz', en: 'a little' },
	{ tr: 'şimdi', en: 'now' },
	{ tr: 'sonra', en: 'later' },
	{ tr: 'önce', en: 'before' },
	{ tr: 'bugün', en: 'today' },
	{ tr: 'yarın', en: 'tomorrow' },
	{ tr: 'dün', en: 'yesterday' },
	{ tr: 'gün', en: 'day' },
	{ tr: 'gece', en: 'night' },
	{ tr: 'zaman', en: 'time' },
	{ tr: 'su', en: 'water' },
	{ tr: 'ekmek', en: 'bread' },
	{ tr: 'çay', en: 'tea' },
	{ tr: 'kahve', en: 'coffee' },
	{ tr: 'süt', en: 'milk' },
	{ tr: 'et', en: 'meat' },
	{ tr: 'meyve', en: 'fruit' },
	{ tr: 'sebze', en: 'vegetable' },
	{ tr: 'ev', en: 'house' },
	{ tr: 'araba', en: 'car' },
	{ tr: 'kitap', en: 'book' },
	{ tr: 'kalem', en: 'pen' },
	{ tr: 'masa', en: 'table' },
	{ tr: 'sandalye', en: 'chair' },
	{ tr: 'kapı', en: 'door' },
	{ tr: 'pencere', en: 'window' },
	{ tr: 'anne', en: 'mother' },
	{ tr: 'baba', en: 'father' },
	{ tr: 'kardeş', en: 'sibling' },
	{ tr: 'arkadaş', en: 'friend' },
	{ tr: 'insan', en: 'person' },
	{ tr: 'çocuk', en: 'child' },
	{ tr: 'kadın', en: 'woman' },
	{ tr: 'erkek', en: 'man' },
	{ tr: 'bir', en: 'one' },
	{ tr: 'iki', en: 'two' },
	{ tr: 'üç', en: 'three' },
	{ tr: 'dört', en: 'four' },
	{ tr: 'beş', en: 'five' },
	{ tr: 'altı', en: 'six' },
	{ tr: 'yedi', en: 'seven' },
	{ tr: 'sekiz', en: 'eight' },
	{ tr: 'dokuz', en: 'nine' },
	{ tr: 'on', en: 'ten' },
	{ tr: 'bu', en: 'this' },
	{ tr: 'şu', en: 'that' },
	{ tr: 'ne', en: 'what' },
	{ tr: 'nerede', en: 'where' },
	{ tr: 'ne zaman', en: 'when' },
	{ tr: 'nasıl', en: 'how' },
	{ tr: 'neden', en: 'why' },
	{ tr: 'kim', en: 'who' },
	{ tr: 'ben', en: 'I' },
	{ tr: 'sen', en: 'you' },
	{ tr: 'biz', en: 'we' },
	{ tr: 'siz', en: 'you (plural)' },
	{ tr: 'onlar', en: 'they' },
	{ tr: 'burada', en: 'here' },
	{ tr: 'orada', en: 'there' },
	{ tr: 'için', en: 'for' },
	{ tr: 'ile', en: 'with' },
	{ tr: 've', en: 'and' },
	{ tr: 'ama', en: 'but' },
	{ tr: 'veya', en: 'or' },
	{ tr: 'çünkü', en: 'because' },
	{ tr: 'eğer', en: 'if' },
	{ tr: 'her', en: 'every' },
	{ tr: 'sadece', en: 'only' },
	{ tr: 'daha', en: 'more' },
	{ tr: 'en', en: 'most' },
	{ tr: 'gibi', en: 'like' },
	{ tr: 'kadar', en: 'until' },
	{ tr: 'şey', en: 'thing' },
	{ tr: 'değil', en: 'not' },
	{ tr: 'var', en: 'there is' },
	{ tr: 'yok', en: 'there is not' },
	{ tr: 'gel', en: 'come' },
	{ tr: 'git', en: 'go' },
	{ tr: 'al', en: 'take' },
	{ tr: 'ver', en: 'give' },
	{ tr: 'yap', en: 'do' },
	{ tr: 'gör', en: 'see' },
	{ tr: 'bil', en: 'know' },
	{ tr: 'istemek', en: 'want' },
	{ tr: 'söyle', en: 'say' },
	{ tr: 'bekle', en: 'wait' },
	{ tr: 'aç', en: 'open' },
	{ tr: 'kapat', en: 'close' },
	{ tr: 'oku', en: 'read' },
	{ tr: 'yaz', en: 'write' },
	{ tr: 'dinle', en: 'listen' },
	{ tr: 'konuş', en: 'speak' },
	{ tr: 'anla', en: 'understand' },
	{ tr: 'bilmiyorum', en: 'I don\'t know' },
	{ tr: 'belki', en: 'maybe' },
	{ tr: 'hadi', en: 'come on' },
	{ tr: 'hoşça kal', en: 'goodbye' },
	{ tr: 'günaydın', en: 'good morning' },
	{ tr: 'iyi akşamlar', en: 'good evening' },
	{ tr: 'iyi geceler', en: 'good night' },
	{ tr: 'rica ederim', en: 'you\'re welcome' },
	{ tr: 'özür dilerim', en: 'sorry' },
	{ tr: 'akşam', en: 'evening' },
	{ tr: 'sabah', en: 'morning' },
	{ tr: 'hafta', en: 'week' },
	{ tr: 'ay', en: 'month' },
	{ tr: 'yıl', en: 'year' },
	{ tr: 'saat', en: 'hour' },
	{ tr: 'dakika', en: 'minute' },
	{ tr: 'saniye', en: 'second' },
	{ tr: 'pazartesi', en: 'Monday' },
	{ tr: 'salı', en: 'Tuesday' },
	{ tr: 'çarşamba', en: 'Wednesday' },
	{ tr: 'perşembe', en: 'Thursday' },
	{ tr: 'cuma', en: 'Friday' },
	{ tr: 'cumartesi', en: 'Saturday' },
	{ tr: 'pazar', en: 'Sunday' },
	{ tr: 'ilkbahar', en: 'spring' },
	{ tr: 'sonbahar', en: 'autumn' },
	{ tr: 'kış', en: 'winter' },
	{ tr: 'hava', en: 'weather' },
	{ tr: 'güneş', en: 'sun' },
	{ tr: 'yağmur', en: 'rain' },
	{ tr: 'kar', en: 'snow' },
	{ tr: 'rüzgar', en: 'wind' },
	{ tr: 'sıcak', en: 'hot' },
	{ tr: 'soğuk', en: 'cold' },
	{ tr: 'ılık', en: 'warm' },
	{ tr: 'serin', en: 'cool' },
	{ tr: 'bulut', en: 'cloud' },
	{ tr: 'gökyüzü', en: 'sky' },
	{ tr: 'renk', en: 'color' },
	{ tr: 'kırmızı', en: 'red' },
	{ tr: 'mavi', en: 'blue' },
	{ tr: 'yeşil', en: 'green' },
	{ tr: 'sarı', en: 'yellow' },
	{ tr: 'turuncu', en: 'orange' },
	{ tr: 'mor', en: 'purple' },
	{ tr: 'siyah', en: 'black' },
	{ tr: 'beyaz', en: 'white' },
	{ tr: 'gri', en: 'gray' },
	{ tr: 'kahverengi', en: 'brown' },
	{ tr: 'pembe', en: 'pink' },
	{ tr: 'vücut', en: 'body' },
	{ tr: 'baş', en: 'head' },
	{ tr: 'yüz', en: 'face' },
	{ tr: 'göz', en: 'eye' },
	{ tr: 'kulak', en: 'ear' },
	{ tr: 'burun', en: 'nose' },
	{ tr: 'ağız', en: 'mouth' },
	{ tr: 'diş', en: 'tooth' },
	{ tr: 'dil', en: 'tongue' },
	{ tr: 'el', en: 'hand' },
	{ tr: 'parmak', en: 'finger' },
	{ tr: 'ayak', en: 'foot' },
	{ tr: 'bacak', en: 'leg' },
	{ tr: 'kol', en: 'arm' },
	{ tr: 'kalp', en: 'heart' },
	{ tr: 'saç', en: 'hair' },
	{ tr: 'deri', en: 'skin' },
	{ tr: 'kan', en: 'blood' },
	{ tr: 'ağrı', en: 'pain' },
	{ tr: 'hasta', en: 'sick' },
	{ tr: 'ilaç', en: 'medicine' },
	{ tr: 'doktor', en: 'doctor' },
	{ tr: 'hastane', en: 'hospital' },
	{ tr: 'şehir', en: 'city' },
	{ tr: 'köy', en: 'village' },
	{ tr: 'ülke', en: 'country' },
	{ tr: 'cadde', en: 'street' },
	{ tr: 'yol', en: 'road' },
	{ tr: 'köprü', en: 'bridge' },
	{ tr: 'park', en: 'park' },
	{ tr: 'market', en: 'market' },
	{ tr: 'mağaza', en: 'shop' },
	{ tr: 'restoran', en: 'restaurant' },
	{ tr: 'otel', en: 'hotel' },
	{ tr: 'okul', en: 'school' },
	{ tr: 'üniversite', en: 'university' },
	{ tr: 'havaalanı', en: 'airport' },
	{ tr: 'istasyon', en: 'station' },
	{ tr: 'tren', en: 'train' },
	{ tr: 'otobüs', en: 'bus' },
	{ tr: 'uçak', en: 'airplane' },
	{ tr: 'gemi', en: 'ship' },
	{ tr: 'bisiklet', en: 'bicycle' },
	{ tr: 'taksi', en: 'taxi' },
	{ tr: 'bilet', en: 'ticket' },
	{ tr: 'pasaport', en: 'passport' },
	{ tr: 'para', en: 'money' },
	{ tr: 'fiyat', en: 'price' },
	{ tr: 'pahalı', en: 'expensive' },
	{ tr: 'ucuz', en: 'cheap' },
	{ tr: 'bedava', en: 'free' },
	{ tr: 'iş', en: 'work' },
	{ tr: 'işçi', en: 'worker' },
	{ tr: 'patron', en: 'boss' },
	{ tr: 'maaş', en: 'salary' },
	{ tr: 'ofis', en: 'office' },
	{ tr: 'toplantı', en: 'meeting' },
	{ tr: 'proje', en: 'project' },
	{ tr: 'sorun', en: 'problem' },
	{ tr: 'çözüm', en: 'solution' },
	{ tr: 'fikir', en: 'idea' },
	{ tr: 'plan', en: 'plan' },
	{ tr: 'haber', en: 'news' },
	{ tr: 'gazete', en: 'newspaper' },
	{ tr: 'televizyon', en: 'television' },
	{ tr: 'radyo', en: 'radio' },
	{ tr: 'telefon', en: 'telephone' },
	{ tr: 'bilgisayar', en: 'computer' },
	{ tr: 'internet', en: 'internet' },
	{ tr: 'e-posta', en: 'email' },
	{ tr: 'mesaj', en: 'message' },
	{ tr: 'oyun', en: 'game' },
	{ tr: 'müzik', en: 'music' },
	{ tr: 'şarkı', en: 'song' },
	{ tr: 'film', en: 'movie' },
	{ tr: 'spor', en: 'sport' },
	{ tr: 'futbol', en: 'football' },
	{ tr: 'yüzme', en: 'swimming' },
	{ tr: 'koşu', en: 'running' },
	{ tr: 'tatil', en: 'holiday' },
	{ tr: 'gezi', en: 'trip' },
	{ tr: 'seyahat', en: 'travel' },
	{ tr: 'harita', en: 'map' },
	{ tr: 'kuzey', en: 'north' },
	{ tr: 'güney', en: 'south' },
	{ tr: 'doğu', en: 'east' },
	{ tr: 'batı', en: 'west' },
	{ tr: 'sol', en: 'left' },
	{ tr: 'sağ', en: 'right' },
	{ tr: 'düz', en: 'straight' },
	{ tr: 'yakın', en: 'near' },
	{ tr: 'uzak', en: 'far' },
	{ tr: 'iç', en: 'inside' },
	{ tr: 'dış', en: 'outside' },
	{ tr: 'üst', en: 'top' },
	{ tr: 'alt', en: 'bottom' },
	{ tr: 'orta', en: 'middle' },
	{ tr: 'yan', en: 'side' },
	{ tr: 'ön', en: 'front' },
	{ tr: 'arka', en: 'back' },
	{ tr: 'etraf', en: 'around' },
	{ tr: 'arasında', en: 'between' },
	{ tr: 'içinde', en: 'inside' },
	{ tr: 'üzerinde', en: 'on' },
	{ tr: 'altında', en: 'under' },
	{ tr: 'karşı', en: 'against' },
	{ tr: 'doğru', en: 'correct' },
	{ tr: 'yanlış', en: 'wrong' },
	{ tr: 'kolay', en: 'easy' },
	{ tr: 'zor', en: 'difficult' },
	{ tr: 'hızlı', en: 'fast' },
	{ tr: 'yavaş', en: 'slow' },
	{ tr: 'erken', en: 'early' },
	{ tr: 'geç', en: 'late' },
	{ tr: 'uzun', en: 'long' },
	{ tr: 'kısa', en: 'short' },
	{ tr: 'geniş', en: 'wide' },
	{ tr: 'dar', en: 'narrow' },
	{ tr: 'yüksek', en: 'high' },
	{ tr: 'alçak', en: 'low' },
	{ tr: 'derin', en: 'deep' },
	{ tr: 'ağır', en: 'heavy' },
	{ tr: 'hafif', en: 'light' },
	{ tr: 'dolu', en: 'full' },
	{ tr: 'boş', en: 'empty' },
	{ tr: 'temiz', en: 'clean' },
	{ tr: 'kirli', en: 'dirty' },
	{ tr: 'ıslak', en: 'wet' },
	{ tr: 'kuru', en: 'dry' },
	{ tr: 'sert', en: 'hard' },
	{ tr: 'yumuşak', en: 'soft' },
	{ tr: 'keskin', en: 'sharp' },
	{ tr: 'kör', en: 'dull' },
	{ tr: 'tatlı', en: 'sweet' },
	{ tr: 'acı', en: 'bitter' },
	{ tr: 'ekşi', en: 'sour' },
	{ tr: 'tuzlu', en: 'salty' },
	{ tr: 'lezzetli', en: 'delicious' },
	{ tr: 'tatsız', en: 'tasteless' },
	{ tr: 'tok', en: 'full' },
	{ tr: 'susuz', en: 'thirsty' },
	{ tr: 'yorgun', en: 'tired' },
	{ tr: 'uykusuz', en: 'sleepless' },
	{ tr: 'mutlu', en: 'happy' },
	{ tr: 'üzgün', en: 'sad' },
	{ tr: 'kızgın', en: 'angry' },
	{ tr: 'korku', en: 'fear' },
	{ tr: 'sevgi', en: 'love' },
	{ tr: 'nefret', en: 'hatred' },
	{ tr: 'umut', en: 'hope' },
	{ tr: 'hayal', en: 'dream' },
	{ tr: 'gerçek', en: 'truth' },
	{ tr: 'yalan', en: 'lie' },
	{ tr: 'güven', en: 'trust' },
	{ tr: 'şans', en: 'luck' },
	{ tr: 'başarı', en: 'success' },
	{ tr: 'başarısızlık', en: 'failure' },
	{ tr: 'deneyim', en: 'experience' },
	{ tr: 'bilgi', en: 'knowledge' },
	{ tr: 'eğitim', en: 'education' },
	{ tr: 'öğrenci', en: 'student' },
	{ tr: 'öğretmen', en: 'teacher' },
	{ tr: 'ders', en: 'lesson' },
	{ tr: 'sınav', en: 'exam' },
	{ tr: 'soru', en: 'question' },
	{ tr: 'cevap', en: 'answer' },
	{ tr: 'lisan', en: 'language' },
	{ tr: 'kelime', en: 'word' },
	{ tr: 'cümle', en: 'sentence' },
	{ tr: 'anlam', en: 'meaning' },
	{ tr: 'çeviri', en: 'translation' },
	{ tr: 'sözlük', en: 'dictionary' },
	{ tr: 'hayvan', en: 'animal' },
	{ tr: 'köpek', en: 'dog' },
	{ tr: 'kedi', en: 'cat' },
	{ tr: 'kuş', en: 'bird' },
	{ tr: 'balık', en: 'fish' },
	{ tr: 'at', en: 'horse' },
	{ tr: 'inek', en: 'cow' },
	{ tr: 'tavuk', en: 'chicken' },
	{ tr: 'arı', en: 'bee' },
	{ tr: 'ağaç', en: 'tree' },
	{ tr: 'çiçek', en: 'flower' },
	{ tr: 'ot', en: 'grass' },
	{ tr: 'dağ', en: 'mountain' },
	{ tr: 'deniz', en: 'sea' },
	{ tr: 'göl', en: 'lake' },
	{ tr: 'nehir', en: 'river' },
	{ tr: 'ada', en: 'island' },
	{ tr: 'kum', en: 'sand' },
	{ tr: 'taş', en: 'stone' },
	{ tr: 'toprak', en: 'soil' },
	{ tr: 'ateş', en: 'fire' },
	{ tr: 'duman', en: 'smoke' },
	{ tr: 'ışık', en: 'light' },
	{ tr: 'karanlık', en: 'darkness' },
	{ tr: 'gölge', en: 'shadow' },
	{ tr: 'ses', en: 'sound' },
	{ tr: 'sessizlik', en: 'silence' },
	{ tr: 'koku', en: 'smell' },
	{ tr: 'tat', en: 'taste' },
	{ tr: 'dokunmak', en: 'to touch' },
	{ tr: 'duymak', en: 'to hear' },
	{ tr: 'koklamak', en: 'to smell' },
	{ tr: 'tatmak', en: 'to taste' },
	{ tr: 'düşünmek', en: 'to think' },
	{ tr: 'hatırlamak', en: 'to remember' },
	{ tr: 'unutmak', en: 'to forget' },
	{ tr: 'öğrenmek', en: 'to learn' },
	{ tr: 'öğretmek', en: 'to teach' },
	{ tr: 'denemek', en: 'to try' },
	{ tr: 'başarmak', en: 'to succeed' },
	{ tr: 'başlamak', en: 'to start' },
	{ tr: 'bitirmek', en: 'to finish' },
	{ tr: 'devam etmek', en: 'to continue' },
	{ tr: 'durmak', en: 'to stop' },
	{ tr: 'değiştirmek', en: 'to change' },
	{ tr: 'seçmek', en: 'to choose' },
	{ tr: 'karar vermek', en: 'to decide' },
	{ tr: 'ihtiyaç duymak', en: 'to need' },
	{ tr: 'sevmek', en: 'to love' },
	{ tr: 'nefret etmek', en: 'to hate' },
	{ tr: 'beğenmek', en: 'to like' },
	{ tr: 'korkmak', en: 'to fear' },
	{ tr: 'umut etmek', en: 'to hope' },
	{ tr: 'inanmak', en: 'to believe' },
	{ tr: 'sanmak', en: 'to suppose' },
	{ tr: 'bulmak', en: 'to find' },
	{ tr: 'kaybetmek', en: 'to lose' },
	{ tr: 'aramak', en: 'to search' },
	{ tr: 'saklamak', en: 'to hide' },
	{ tr: 'göstermek', en: 'to show' },
	{ tr: 'almak', en: 'to take' },
	{ tr: 'getirmek', en: 'to bring' },
	{ tr: 'götürmek', en: 'to take away' },
	{ tr: 'taşımak', en: 'to carry' },
	{ tr: 'bırakmak', en: 'to leave' },
	{ tr: 'koymak', en: 'to put' },
	{ tr: 'çıkarmak', en: 'to remove' },
	{ tr: 'eklemek', en: 'to add' },
	{ tr: 'çoğaltmak', en: 'to multiply' },
	{ tr: 'bölmek', en: 'to divide' },
	{ tr: 'yemek', en: 'to eat' },
	{ tr: 'içmek', en: 'to drink' },
	{ tr: 'uyumak', en: 'to sleep' },
	{ tr: 'uyanmak', en: 'to wake up' },
	{ tr: 'giymek', en: 'to wear' },
	{ tr: 'yıkamak', en: 'to wash' },
	{ tr: 'temizlemek', en: 'to clean' },
	{ tr: 'pişirmek', en: 'to cook' },
	{ tr: 'satın almak', en: 'to buy' },
	{ tr: 'satmak', en: 'to sell' },
	{ tr: 'ödeme yapmak', en: 'to pay' },
	{ tr: 'borç', en: 'debt' },
	{ tr: 'hediye', en: 'gift' },
	{ tr: 'doğum günü', en: 'birthday' },
	{ tr: 'düğün', en: 'wedding' },
	{ tr: 'parti', en: 'party' },
	{ tr: 'kutlama', en: 'celebration' },
	{ tr: 'bayram', en: 'holiday' },
	{ tr: 'yılbaşı', en: 'New Year' },
	{ tr: 'noel', en: 'Christmas' },
	{ tr: 'ramazan', en: 'Ramadan' },
	{ tr: 'kurtulmak', en: 'to escape' },
	{ tr: 'takip etmek', en: 'to follow' },
	{ tr: 'lider', en: 'leader' },
	{ tr: 'takım', en: 'team' },
	{ tr: 'grup', en: 'group' },
	{ tr: 'tek', en: 'single' },
	{ tr: 'çift', en: 'couple' },
	{ tr: 'aile', en: 'family' },
	{ tr: 'komşu', en: 'neighbor' },
	{ tr: 'misafir', en: 'guest' },
	{ tr: 'ev sahibi', en: 'host' },
	{ tr: 'yabancı', en: 'foreigner' },
	{ tr: 'vatandaş', en: 'citizen' },
	{ tr: 'hükümet', en: 'government' },
	{ tr: 'kanun', en: 'law' },
	{ tr: 'hak', en: 'right' },
	{ tr: 'özgürlük', en: 'freedom' },
	{ tr: 'adalet', en: 'justice' },
	{ tr: 'savaş', en: 'war' },
	{ tr: 'barış', en: 'peace' },
	{ tr: 'tehlike', en: 'danger' },
	{ tr: 'güvenlik', en: 'security' },
	{ tr: 'yardım', en: 'help' },
	{ tr: 'destek', en: 'support' },
	{ tr: 'izin', en: 'permission' },
	{ tr: 'yasak', en: 'forbidden' },
	{ tr: 'zorunlu', en: 'mandatory' },
	{ tr: 'isteğe bağlı', en: 'optional' },
	{ tr: 'normal', en: 'normal' },
	{ tr: 'özel', en: 'special' },
	{ tr: 'genel', en: 'general' },
	{ tr: 'basit', en: 'simple' },
	{ tr: 'karmaşık', en: 'complex' },
	{ tr: 'önemli', en: 'important' },
	{ tr: 'gerekli', en: 'necessary' },
	{ tr: 'mümkün', en: 'possible' },
	{ tr: 'imkansız', en: 'impossible' },
	{ tr: 'kesin', en: 'certain' },
	{ tr: 'şüpheli', en: 'doubtful' },
	{ tr: 'her zaman', en: 'always' },
	{ tr: 'hiçbir zaman', en: 'never' },
	{ tr: 'bazen', en: 'sometimes' },
	{ tr: 'genellikle', en: 'usually' },
	{ tr: 'sık sık', en: 'often' },
	{ tr: 'nadiren', en: 'rarely' },
	{ tr: 'henüz', en: 'yet' },
	{ tr: 'zaten', en: 'already' },
	{ tr: 'hala', en: 'still' },
	{ tr: 'artık', en: 'anymore' },
	{ tr: 'hemen', en: 'immediately' },
	{ tr: 'yavaşça', en: 'slowly' },
	{ tr: 'hızlıca', en: 'quickly' },
	{ tr: 'dikkatli', en: 'careful' },
	{ tr: 'dikkatsiz', en: 'careless' },
	{ tr: 'sakin', en: 'calm' },
	{ tr: 'heyecanlı', en: 'excited' },
	{ tr: 'meraklı', en: 'curious' },
	{ tr: 'sabırlı', en: 'patient' },
	{ tr: 'sabırsız', en: 'impatient' },
	{ tr: 'cömert', en: 'generous' },
	{ tr: 'cimri', en: 'stingy' },
	{ tr: 'cesur', en: 'brave' },
	{ tr: 'korkak', en: 'cowardly' },
	{ tr: 'dürüst', en: 'honest' },
	{ tr: 'yalancı', en: 'liar' },
	{ tr: 'nazik', en: 'kind' },
	{ tr: 'kaba', en: 'rude' },
	{ tr: 'akıllı', en: 'smart' },
	{ tr: 'aptal', en: 'stupid' },
	{ tr: 'zengin', en: 'rich' },
	{ tr: 'fakir', en: 'poor' },
	{ tr: 'ünlü', en: 'famous' },
	{ tr: 'bilinmeyen', en: 'unknown' },
	{ tr: 'acıkmak', en: 'to get hungry' },
	{ tr: 'açıklamak', en: 'to explain' },
	{ tr: 'adım', en: 'step' },
	{ tr: 'affetmek', en: 'to forgive' },
	{ tr: 'ağlamak', en: 'to cry' },
	{ tr: 'akşam yemeği', en: 'dinner' },
	{ tr: 'altın', en: 'gold' },
	{ tr: 'anlamak', en: 'to understand' },
	{ tr: 'anneanne', en: 'grandmother' },
	{ tr: 'asansör', en: 'elevator' },
	{ tr: 'aslında', en: 'actually' },
	{ tr: 'atmak', en: 'to throw' },
	{ tr: 'avrupa', en: 'Europe' },
	{ tr: 'ayakta', en: 'standing' },
	{ tr: 'ayna', en: 'mirror' },
	{ tr: 'aynı', en: 'same' },
	{ tr: 'balkon', en: 'balcony' },
	{ tr: 'banka', en: 'bank' },
	{ tr: 'banyo', en: 'bathroom' },
	{ tr: 'bebek', en: 'baby' },
	{ tr: 'beklemek', en: 'to wait' },
	{ tr: 'belge', en: 'document' },
	{ tr: 'binmek', en: 'to get on' },
	{ tr: 'bira', en: 'beer' },
	{ tr: 'birlikte', en: 'together' },
	{ tr: 'bölge', en: 'region' },
	{ tr: 'büro', en: 'office' },
	{ tr: 'cam', en: 'glass' },
	{ tr: 'ceket', en: 'jacket' },
	{ tr: 'cephe', en: 'front' },
	{ tr: 'cuma namazı', en: 'Friday prayer' },
	{ tr: 'çalışmak', en: 'to work' },
	{ tr: 'çanta', en: 'bag' },
	{ tr: 'çekmek', en: 'to pull' },
	{ tr: 'çevirmek', en: 'to translate' },
	{ tr: 'çıkmak', en: 'to go out' },
	{ tr: 'çikolata', en: 'chocolate' },
	{ tr: 'çocukluk', en: 'childhood' },
	{ tr: 'çorba', en: 'soup' },
	{ tr: 'dağcılık', en: 'mountaineering' },
	{ tr: 'davet', en: 'invitation' },
	{ tr: 'davet etmek', en: 'to invite' },
	{ tr: 'defa', en: 'time' },
	{ tr: 'değer', en: 'value' },
	{ tr: 'demek', en: 'to mean' },
	{ tr: 'deprem', en: 'earthquake' },
	{ tr: 'derece', en: 'degree' },
	{ tr: 'dikkat', en: 'attention' },
	{ tr: 'dil bilgisi', en: 'grammar' },
	{ tr: 'doğal', en: 'natural' },
	{ tr: 'doğmak', en: 'to be born' },
	{ tr: 'dondurma', en: 'ice cream' },
	{ tr: 'dua', en: 'prayer' },
	{ tr: 'duvar', en: 'wall' },
	{ tr: 'duygu', en: 'emotion' },
	{ tr: 'dünya', en: 'world' },
	{ tr: 'düşman', en: 'enemy' },
	{ tr: 'düşmek', en: 'to fall' },
	{ tr: 'düzen', en: 'order' },
	{ tr: 'eczane', en: 'pharmacy' },
	{ tr: 'efendi', en: 'gentleman' },
	{ tr: 'elbise', en: 'dress' },
	{ tr: 'elektrik', en: 'electricity' },
	{ tr: 'elma', en: 'apple' },
	{ tr: 'emek', en: 'labor' },
	{ tr: 'emin', en: 'sure' },
	{ tr: 'erkek kardeş', en: 'brother' },
	{ tr: 'etkili', en: 'effective' },
	{ tr: 'evlenmek', en: 'to marry' },
	{ tr: 'evli', en: 'married' },
	{ tr: 'eylem', en: 'action' },
	{ tr: 'fabrika', en: 'factory' },
	{ tr: 'fark', en: 'difference' },
	{ tr: 'farklı', en: 'different' },
	{ tr: 'fırsat', en: 'opportunity' },
	{ tr: 'fiyat listesi', en: 'price list' },
	{ tr: 'garip', en: 'strange' },
	{ tr: 'gazeteci', en: 'journalist' },
	{ tr: 'gece yarısı', en: 'midnight' },
	{ tr: 'geçen', en: 'last' },
	{ tr: 'geçmiş', en: 'past' },
	{ tr: 'geçmek', en: 'to pass' },
	{ tr: 'gelin', en: 'bride' },
	{ tr: 'gelir', en: 'income' },
	{ tr: 'genç', en: 'young' },
	{ tr: 'gerçekleşmek', en: 'to come true' },
	{ tr: 'gerek', en: 'need' },
	{ tr: 'germek', en: 'to stretch' },
	{ tr: 'giriş', en: 'entrance' },
	{ tr: 'gişe', en: 'counter' },
	{ tr: 'görmek', en: 'to see' },
	{ tr: 'gözyaşı', en: 'tear' },
	{ tr: 'gülmek', en: 'to laugh' },
	{ tr: 'gümüş', en: 'silver' },
	{ tr: 'günlük', en: 'daily' },
	{ tr: 'güvenmek', en: 'to trust' },
	{ tr: 'haber vermek', en: 'to inform' },
	{ tr: 'hakkında', en: 'about' },
	{ tr: 'hal', en: 'state' },
	{ tr: 'hata', en: 'mistake' },
	{ tr: 'havlu', en: 'towel' },
	{ tr: 'hayal etmek', en: 'to imagine' },
	{ tr: 'hayat', en: 'life' },
	{ tr: 'hayvanat bahçesi', en: 'zoo' },
	{ tr: 'hazır', en: 'ready' },
	{ tr: 'hazırlamak', en: 'to prepare' },
	{ tr: 'hediye etmek', en: 'to give a gift' },
	{ tr: 'hemen hemen', en: 'almost' },
	{ tr: 'hesap', en: 'bill' },
	{ tr: 'hikaye', en: 'story' },
	{ tr: 'hoş', en: 'pleasant' },
	{ tr: 'hoşlanmak', en: 'to enjoy' },
	{ tr: 'ıslanmak', en: 'to get wet' },
	{ tr: 'içecek', en: 'beverage' },
	{ tr: 'içeri', en: 'inside' },
	{ tr: 'ihtiyar', en: 'elderly' },
	{ tr: 'ilan', en: 'announcement' },
	{ tr: 'imza', en: 'signature' },
	{ tr: 'inanılmaz', en: 'incredible' },
	{ tr: 'ince', en: 'thin' },
	{ tr: 'işaret', en: 'sign' },
	{ tr: 'işe yaramak', en: 'to be useful' },
	{ tr: 'işlem', en: 'transaction' },
	{ tr: 'ithalat', en: 'import' },
	{ tr: 'izin vermek', en: 'to allow' },
	{ tr: 'kabul etmek', en: 'to accept' },
	{ tr: 'kafe', en: 'cafe' },
	{ tr: 'kaldırmak', en: 'to lift' },
	{ tr: 'kalmak', en: 'to stay' },
	{ tr: 'kamera', en: 'camera' },
	{ tr: 'kamp', en: 'camp' },
	{ tr: 'kanıt', en: 'evidence' },
	{ tr: 'kapalı', en: 'closed' },
	{ tr: 'karanfil', en: 'carnation' },
	{ tr: 'kart', en: 'card' },
	{ tr: 'kasa', en: 'cash register' },
	{ tr: 'kayak', en: 'skiing' },
	{ tr: 'kaynak', en: 'source' },
	{ tr: 'kaza', en: 'accident' },
	{ tr: 'kazanmak', en: 'to win' },
	{ tr: 'kebap', en: 'kebab' },
	{ tr: 'keder', en: 'sorrow' },
	{ tr: 'kent', en: 'city' },
	{ tr: 'kılavuz', en: 'guide' },
	{ tr: 'kırmak', en: 'to break' },
	{ tr: 'kıyafet', en: 'clothing' },
	{ tr: 'kıyma', en: 'minced meat' },
	{ tr: 'kız kardeş', en: 'sister' },
	{ tr: 'kilo', en: 'kilogram' },
	{ tr: 'kimlik', en: 'identity' },
	{ tr: 'kira', en: 'rent' },
	{ tr: 'kiracı', en: 'tenant' },
	{ tr: 'kiralık', en: 'for rent' },
	{ tr: 'kitaplık', en: 'bookshelf' },
	{ tr: 'koltuk', en: 'armchair' },
	{ tr: 'konferans', en: 'conference' },
	{ tr: 'konu', en: 'topic' },
	{ tr: 'korku filmi', en: 'horror movie' },
	{ tr: 'koyu', en: 'dark' },
	{ tr: 'köpek balığı', en: 'shark' },
	{ tr: 'körfez', en: 'gulf' },
	{ tr: 'kullanmak', en: 'to use' },
	{ tr: 'kültür', en: 'culture' },
	{ tr: 'kurabiye', en: 'cookie' },
	{ tr: 'kurmak', en: 'to set up' },
	{ tr: 'kurum', en: 'institution' },
	{ tr: 'kuşku', en: 'doubt' },
	{ tr: 'kutu', en: 'box' },
	{ tr: 'kuzu', en: 'lamb' },
	{ tr: 'küçümsemek', en: 'to underestimate' },
	{ tr: 'küfür', en: 'curse' },
	{ tr: 'kürek', en: 'oar' },
	{ tr: 'laboratuvar', en: 'laboratory' },
	{ tr: 'lahana', en: 'cabbage' },
	{ tr: 'lazım', en: 'necessary' },
	{ tr: 'liste', en: 'list' },
	{ tr: 'lokanta', en: 'restaurant' },
	{ tr: 'makine', en: 'machine' },
	{ tr: 'mal', en: 'goods' },
	{ tr: 'mangal', en: 'barbecue' },
	{ tr: 'mantar', en: 'mushroom' },
	{ tr: 'masraf', en: 'expense' },
	{ tr: 'mektup', en: 'letter' },
	{ tr: 'merak', en: 'curiosity' },
	{ tr: 'merkez', en: 'center' },
	{ tr: 'mesafe', en: 'distance' },
	{ tr: 'metin', en: 'text' },
	{ tr: 'mevsim', en: 'season' },
	{ tr: 'mevcut', en: 'available' },
	{ tr: 'meydan', en: 'square' },
	{ tr: 'meyve suyu', en: 'fruit juice' },
	{ tr: 'müşteri', en: 'customer' },
	{ tr: 'nakliye', en: 'shipping' },
	{ tr: 'nakit', en: 'cash' },
	{ tr: 'nar', en: 'pomegranate' },
	{ tr: 'nedenle', en: 'therefore' },
	{ tr: 'niyet', en: 'intention' },
	{ tr: 'nişan', en: 'engagement' },
	{ tr: 'numara', en: 'number' },
	{ tr: 'ocak', en: 'stove' },
	{ tr: 'oda', en: 'room' },
	{ tr: 'ödül', en: 'prize' },
	{ tr: 'öğle yemeği', en: 'lunch' },
	{ tr: 'öğretim', en: 'teaching' },
	{ tr: 'ölçü', en: 'measure' },
	{ tr: 'ölmek', en: 'to die' },
	{ tr: 'önem', en: 'importance' },
	{ tr: 'önlemek', en: 'to prevent' },
	{ tr: 'örnek', en: 'example' },
	{ tr: 'örtü', en: 'cover' },
	{ tr: 'övmek', en: 'to praise' },
	{ tr: 'öykü', en: 'tale' },
	{ tr: 'özel gün', en: 'special day' },
	{ tr: 'özellik', en: 'feature' },
	{ tr: 'özellikle', en: 'especially' },
	{ tr: 'özet', en: 'summary' },
	{ tr: 'paket', en: 'package' },
	{ tr: 'palto', en: 'coat' },
	{ tr: 'pamuk', en: 'cotton' },
	{ tr: 'pantalon', en: 'trousers' },
	{ tr: 'peynir', en: 'cheese' },
	{ tr: 'pilot', en: 'pilot' },
	{ tr: 'polis', en: 'police' },
	{ tr: 'portakal', en: 'orange' },
	{ tr: 'posta', en: 'mail' },
	{ tr: 'program', en: 'program' },
	{ tr: 'rahat', en: 'comfortable' },
	{ tr: 'rakip', en: 'competitor' },
	{ tr: 'randevu', en: 'appointment' },
	{ tr: 'reçel', en: 'jam' },
	{ tr: 'reklam', en: 'advertisement' },
	{ tr: 'resim', en: 'picture' },
	{ tr: 'rica', en: 'request' },
	{ tr: 'rol', en: 'role' },
	{ tr: 'rüya', en: 'dream' },
	{ tr: 'sabun', en: 'soap' },
	{ tr: 'sade', en: 'plain' },
	{ tr: 'sahil', en: 'coast' },
	{ tr: 'sakin olmak', en: 'to calm down' },
	{ tr: 'salata', en: 'salad' },
	{ tr: 'salon', en: 'living room' },
	{ tr: 'sanat', en: 'art' },
	{ tr: 'sarılmak', en: 'to hug' },
	{ tr: 'satış', en: 'sale' },
	{ tr: 'sayfa', en: 'page' },
	{ tr: 'saygı', en: 'respect' },
	{ tr: 'sayı', en: 'number' },
	{ tr: 'sebep', en: 'reason' },
	{ tr: 'seçenek', en: 'option' },
	{ tr: 'seçim', en: 'election' },
	{ tr: 'sergi', en: 'exhibition' },
	{ tr: 'sertlik', en: 'hardness' },
	{ tr: 'servis', en: 'service' },
	{ tr: 'sessiz', en: 'quiet' },
	{ tr: 'sigara', en: 'cigarette' },
	{ tr: 'sigorta', en: 'insurance' },
	{ tr: 'sınır', en: 'border' },
	{ tr: 'sıra', en: 'row' },
	{ tr: 'sıcaklık', en: 'temperature' },
	{ tr: 'sıkılmak', en: 'to get bored' },
	{ tr: 'sıkıntı', en: 'trouble' },
	{ tr: 'soğan', en: 'onion' },
	{ tr: 'sorumlu', en: 'responsible' },
	{ tr: 'sorumluluk', en: 'responsibility' },
	{ tr: 'süre', en: 'duration' },
	{ tr: 'sürekli', en: 'continuous' },
	{ tr: 'şanslı', en: 'lucky' },
	{ tr: 'şarj', en: 'charge' },
	{ tr: 'şehir merkezi', en: 'city center' },
	{ tr: 'şeker', en: 'sugar' },
	{ tr: 'şikayet', en: 'complaint' },
	{ tr: 'şirket', en: 'company' },
	{ tr: 'şişe', en: 'bottle' },
	{ tr: 'şoför', en: 'driver' },
	{ tr: 'tabak', en: 'plate' },
	{ tr: 'tadına bakmak', en: 'to taste' },
	{ tr: 'tahmin', en: 'guess' },
	{ tr: 'takvim', en: 'calendar' },
	{ tr: 'tamamlamak', en: 'to complete' },
	{ tr: 'tane', en: 'piece' },
	{ tr: 'tanımak', en: 'to recognize' },
	{ tr: 'tanışmak', en: 'to meet' },
	{ tr: 'tarih', en: 'date' },
	{ tr: 'tarif', en: 'recipe' },
	{ tr: 'tasarruf', en: 'savings' },
	{ tr: 'taşımacılık', en: 'transport' },
	{ tr: 'tebrik', en: 'congratulations' },
	{ tr: 'teknik', en: 'technical' },
	{ tr: 'tekrar', en: 'again' },
	{ tr: 'telefon etmek', en: 'to call' },
	{ tr: 'tembel', en: 'lazy' },
	{ tr: 'tercih', en: 'preference' },
	{ tr: 'terlemek', en: 'to sweat' },
	{ tr: 'tesis', en: 'facility' },
	{ tr: 'teşvik', en: 'encouragement' },
	{ tr: 'tıbbi', en: 'medical' },
	{ tr: 'tokat', en: 'slap' },
	{ tr: 'toplam', en: 'total' },
	{ tr: 'trafik', en: 'traffic' },
	{ tr: 'turist', en: 'tourist' },
	{ tr: 'tutmak', en: 'to hold' },
	{ tr: 'tuz', en: 'salt' },
	{ tr: 'tüketmek', en: 'to consume' },
	{ tr: 'tür', en: 'type' },
	{ tr: 'uçak bileti', en: 'plane ticket' },
	{ tr: 'uğramak', en: 'to drop by' },
	{ tr: 'uygun', en: 'suitable' },
	{ tr: 'uygulama', en: 'application' },
	{ tr: 'üzüm', en: 'grape' },
	{ tr: 'vatan', en: 'homeland' },
	{ tr: 'vazgeçmek', en: 'to give up' },
	{ tr: 'vejetaryen', en: 'vegetarian' },
	{ tr: 'vergi', en: 'tax' },
	{ tr: 'vesaire', en: 'et cetera' },
	{ tr: 'vurmak', en: 'to hit' },
	{ tr: 'yabancı dil', en: 'foreign language' },
	{ tr: 'yağ', en: 'oil' },
	{ tr: 'yakıt', en: 'fuel' },
	{ tr: 'yalnız', en: 'alone' },
	{ tr: 'yanıt', en: 'response' },
	{ tr: 'yaprak', en: 'leaf' },
	{ tr: 'yasal', en: 'legal' },
	{ tr: 'yastık', en: 'pillow' },
	{ tr: 'yavaşlamak', en: 'to slow down' },
	{ tr: 'yazı', en: 'writing' },
	{ tr: 'yemek listesi', en: 'menu' },
	{ tr: 'yer', en: 'place' },
	{ tr: 'yetenek', en: 'ability' },
	{ tr: 'yılbaşı ağacı', en: 'Christmas tree' },
	{ tr: 'yolcu', en: 'passenger' },
	{ tr: 'yolculuk', en: 'journey' },
	{ tr: 'yorum', en: 'comment' },
	{ tr: 'yüzük', en: 'ring' },
	{ tr: 'zamanında', en: 'on time' },
	{ tr: 'zarar', en: 'damage' },
	{ tr: 'zehir', en: 'poison' },
	{ tr: 'zemin', en: 'floor' },
	{ tr: 'zenginlik', en: 'wealth' },
	{ tr: 'zeytin', en: 'olive' },
	{ tr: 'abla', en: 'older sister' },
	{ tr: 'abur cubur', en: 'junk food' },
	{ tr: 'acı çekmek', en: 'to suffer' },
	{ tr: 'acil', en: 'urgent' },
	{ tr: 'ad', en: 'name' },
	{ tr: 'adres', en: 'address' },
	{ tr: 'ağaçlık', en: 'wooded' },
	{ tr: 'akıl', en: 'mind' },
	{ tr: 'akıllıca', en: 'wisely' },
	{ tr: 'akrabalık', en: 'relationship' },
	{ tr: 'akşamüzeri', en: 'afternoon' },
	{ tr: 'alışkanlık', en: 'habit' },
	{ tr: 'alışveriş', en: 'shopping' },
	{ tr: 'alışveriş merkezi', en: 'mall' },
	{ tr: 'alkol', en: 'alcohol' },
	{ tr: 'allah', en: 'God' },
	{ tr: 'alt yapı', en: 'infrastructure' },
	{ tr: 'anahtar', en: 'key' },
	{ tr: 'anlaşma', en: 'agreement' },
	{ tr: 'antika', en: 'antique' },
	{ tr: 'ara', en: 'gap' },
	{ tr: 'araba kiralama', en: 'car rental' },
	{ tr: 'aralık', en: 'December' },
	{ tr: 'arıtmak', en: 'to purify' },
	{ tr: 'arkadaşlık', en: 'friendship' },
	{ tr: 'armut', en: 'pear' },
	{ tr: 'aşçı', en: 'chef' },
	{ tr: 'aşk', en: 'love' },
	{ tr: 'aşırı', en: 'excessive' },
	{ tr: 'atık', en: 'waste' },
	{ tr: 'avukat', en: 'lawyer' },
	{ tr: 'ayak parmağı', en: 'toe' },
	{ tr: 'ayarlamak', en: 'to adjust' },
	{ tr: 'aydınlık', en: 'bright' },
	{ tr: 'ayı', en: 'bear' },
	{ tr: 'ayırmak', en: 'to separate' },
	{ tr: 'aynı zamanda', en: 'at the same time' },
	{ tr: 'ayrıca', en: 'additionally' },
	{ tr: 'azalmak', en: 'to decrease' },
	{ tr: 'baharat', en: 'spice' },
	{ tr: 'bahçe', en: 'garden' },
	{ tr: 'bakım', en: 'care' },
	{ tr: 'bakkal', en: 'grocer' },
	{ tr: 'bakteri', en: 'bacteria' },
	{ tr: 'bal', en: 'honey' },
	{ tr: 'balık tutmak', en: 'to fish' },
	{ tr: 'banka kartı', en: 'bank card' },
	{ tr: 'banyo yapmak', en: 'to bathe' },
	{ tr: 'barışçıl', en: 'peaceful' },
	{ tr: 'basın', en: 'press' },
	{ tr: 'başarılı', en: 'successful' },
	{ tr: 'başbakan', en: 'prime minister' },
	{ tr: 'başkent', en: 'capital city' },
	{ tr: 'bavul', en: 'suitcase' },
	{ tr: 'bayat', en: 'stale' },
	{ tr: 'bazı', en: 'some' },
	{ tr: 'belediye', en: 'municipality' },
	{ tr: 'beraber', en: 'together' },
	{ tr: 'berber', en: 'barber' },
	{ tr: 'beyin', en: 'brain' },
	{ tr: 'bıçak', en: 'knife' },
	{ tr: 'bilet gişesi', en: 'ticket office' },
	{ tr: 'bina', en: 'building' },
	{ tr: 'birlik', en: 'union' },
	{ tr: 'biyoloji', en: 'biology' },
	{ tr: 'boğaz', en: 'throat' },
	{ tr: 'boşanmak', en: 'to divorce' },
	{ tr: 'boy', en: 'height' },
	{ tr: 'boya', en: 'paint' },
	{ tr: 'boyun', en: 'neck' },
	{ tr: 'bozuk', en: 'broken' },
	{ tr: 'bölüm', en: 'section' },
	{ tr: 'bütçe', en: 'budget' },
	{ tr: 'büyükanne', en: 'grandmother' },
	{ tr: 'büyükbaba', en: 'grandfather' },
	{ tr: 'büyümek', en: 'to grow' },
	{ tr: 'cami', en: 'mosque' },
	{ tr: 'cehennem', en: 'hell' },
	{ tr: 'cep telefonu', en: 'mobile phone' },
	{ tr: 'cevap vermek', en: 'to answer' },
	{ tr: 'ceza', en: 'punishment' },
	{ tr: 'cinsiyet', en: 'gender' },
	{ tr: 'çabuk', en: 'quick' },
	{ tr: 'çağ', en: 'era' },
	{ tr: 'çalışkan', en: 'hardworking' },
	{ tr: 'çamaşır', en: 'laundry' },
	{ tr: 'çekirdek', en: 'seed' },
	{ tr: 'çevre', en: 'environment' },
	{ tr: 'çeyrek', en: 'quarter' },
	{ tr: 'çiftçi', en: 'farmer' },
	{ tr: 'çikolatalı', en: 'chocolate' },
	{ tr: 'çimento', en: 'cement' },
	{ tr: 'çirkin', en: 'ugly' },
	{ tr: 'çocukça', en: 'childish' },
	{ tr: 'çorap', en: 'sock' },
	{ tr: 'çöp', en: 'garbage' },
	{ tr: 'dağcı', en: 'mountaineer' },
	{ tr: 'damga', en: 'stamp' },
	{ tr: 'davranış', en: 'behavior' },
	{ tr: 'değişim', en: 'exchange' },
	{ tr: 'değnek', en: 'stick' },
	{ tr: 'demir', en: 'iron' },
	{ tr: 'deney', en: 'experiment' },
	{ tr: 'deniz kenarı', en: 'seaside' },
	{ tr: 'depolamak', en: 'to store' },
	{ tr: 'ders çalışmak', en: 'to study' },
	{ tr: 'devlet', en: 'state' },
	{ tr: 'dikkatli olmak', en: 'to be careful' },
	{ tr: 'dilenci', en: 'beggar' },
	{ tr: 'din', en: 'religion' },
	{ tr: 'dinamik', en: 'dynamic' },
	{ tr: 'dinlenmek', en: 'to rest' },
	{ tr: 'diploma', en: 'diploma' },
	{ tr: 'direk', en: 'pole' },
	{ tr: 'direksiyon', en: 'steering wheel' },
	{ tr: 'doğa', en: 'nature' },
	{ tr: 'doğum', en: 'birth' },
	{ tr: 'doküman', en: 'document' },
	{ tr: 'dolap', en: 'cupboard' },
	{ tr: 'dolmuş', en: 'shared taxi' },
	{ tr: 'dondurulmuş', en: 'frozen' },
	{ tr: 'dönem', en: 'period' },
	{ tr: 'dönüş', en: 'return' },
	{ tr: 'dudak', en: 'lip' },
	{ tr: 'durak', en: 'stop' },
	{ tr: 'dut', en: 'mulberry' },
	{ tr: 'düğme', en: 'button' },
	{ tr: 'dükkan', en: 'shop' },
	{ tr: 'düzenli', en: 'regular' },
	{ tr: 'eczacı', en: 'pharmacist' },
	{ tr: 'edebiyat', en: 'literature' },
	{ tr: 'efektif', en: 'effective' },
	{ tr: 'ekip', en: 'team' },
	{ tr: 'ekmek fırını', en: 'bakery' },
	{ tr: 'ekonomi', en: 'economy' },
	{ tr: 'ekran', en: 'screen' },
	{ tr: 'el ele', en: 'hand in hand' },
	{ tr: 'elektronik', en: 'electronic' },
	{ tr: 'emekli', en: 'retired' },
	{ tr: 'emretmek', en: 'to order' },
	{ tr: 'enerji', en: 'energy' },
	{ tr: 'engel', en: 'obstacle' },
	{ tr: 'engelli', en: 'disabled' },
	{ tr: 'enlem', en: 'latitude' },
	{ tr: 'ergen', en: 'teenager' },
	{ tr: 'etiket', en: 'label' },
	{ tr: 'etki', en: 'effect' },
	{ tr: 'evcil', en: 'domestic' },
	{ tr: 'evrak', en: 'papers' },
	{ tr: 'eylül', en: 'September' },
	{ tr: 'fabrikasyon', en: 'manufacturing' },
	{ tr: 'fark etmek', en: 'to notice' },
	{ tr: 'fatura', en: 'invoice' },
	{ tr: 'fayda', en: 'benefit' },
	{ tr: 'felsefe', en: 'philosophy' },
	{ tr: 'feribot', en: 'ferry' },
	{ tr: 'fırın', en: 'oven' },
	{ tr: 'fıstık', en: 'nut' },
	{ tr: 'fiyat etiketi', en: 'price tag' },
	{ tr: 'fotoğraf', en: 'photo' },
	{ tr: 'fotoğrafçı', en: 'photographer' },
	{ tr: 'frekans', en: 'frequency' },
	{ tr: 'fuar', en: 'fair' },
	{ tr: 'garanti', en: 'guarantee' },
	{ tr: 'garson', en: 'waiter' },
	{ tr: 'gaz', en: 'gas' },
	{ tr: 'gece kulübü', en: 'nightclub' },
	{ tr: 'geçerli', en: 'valid' },
	{ tr: 'geçici', en: 'temporary' },
	{ tr: 'geçit', en: 'passage' },
	{ tr: 'gelir vergisi', en: 'income tax' },
	{ tr: 'genişletmek', en: 'to expand' },
	{ tr: 'gerçekten', en: 'really' },
	{ tr: 'geri', en: 'back' },
	{ tr: 'gıda', en: 'food' },
	{ tr: 'giriş ücreti', en: 'entrance fee' },
	{ tr: 'göç', en: 'migration' },
	{ tr: 'göçmen', en: 'immigrant' },
	{ tr: 'gömlek', en: 'shirt' },
	{ tr: 'görev', en: 'duty' },
	{ tr: 'görgü', en: 'manners' },
	{ tr: 'görünüm', en: 'appearance' },
	{ tr: 'gösteri', en: 'show' },
	{ tr: 'gözlemek', en: 'to observe' },
	{ tr: 'gübre', en: 'fertilizer' },
	{ tr: 'güç', en: 'power' },
	{ tr: 'güçlü', en: 'strong' },
	{ tr: 'gül', en: 'rose' },
	{ tr: 'gülümsemek', en: 'to smile' },
	{ tr: 'günlük hayat', en: 'daily life' },
	{ tr: 'gürültü', en: 'noise' },
	{ tr: 'güvenlik görevlisi', en: 'security guard' },
	{ tr: 'güzellik', en: 'beauty' },
	{ tr: 'haberci', en: 'messenger' },
	{ tr: 'hafıza', en: 'memory' },
	{ tr: 'hafta sonu', en: 'weekend' },
	{ tr: 'hakem', en: 'referee' },
	{ tr: 'haklı', en: 'right' },
	{ tr: 'halı', en: 'carpet' },
	{ tr: 'ham', en: 'raw' },
	{ tr: 'hamile', en: 'pregnant' },
	{ tr: 'hamur', en: 'dough' },
	{ tr: 'hap', en: 'pill' },
	{ tr: 'hareket', en: 'movement' },
	{ tr: 'hasat', en: 'harvest' },
	{ tr: 'hasret', en: 'longing' },
	{ tr: 'hasta bakıcı', en: 'nurse' },
	{ tr: 'hayal kırıklığı', en: 'disappointment' },
	{ tr: 'hayatta kalmak', en: 'to survive' },
	{ tr: 'hayır kurumu', en: 'charity' },
	{ tr: 'haziran', en: 'June' },
	{ tr: 'hedef', en: 'target' },
	{ tr: 'hemşire', en: 'nurse' },
	{ tr: 'hesap makinesi', en: 'calculator' },
	{ tr: 'heyecan', en: 'excitement' },
	{ tr: 'hikaye anlatmak', en: 'to tell a story' },
	{ tr: 'hissetmek', en: 'to feel' },
	{ tr: 'hız', en: 'speed' },
	{ tr: 'hızlı tren', en: 'high-speed train' },
	{ tr: 'ılıman', en: 'temperate' },
	{ tr: 'ısı', en: 'heat' },
	{ tr: 'ıspanak', en: 'spinach' },
	{ tr: 'iç çamaşırı', en: 'underwear' },
	{ tr: 'içerik', en: 'content' },
	{ tr: 'içgüdü', en: 'instinct' },
	{ tr: 'içinde bulunmak', en: 'to be in' },
	{ tr: 'il', en: 'province' },
	{ tr: 'ilan vermek', en: 'to advertise' },
	{ tr: 'ilçe', en: 'district' },
	{ tr: 'ileri', en: 'forward' },
	{ tr: 'ilerlemek', en: 'to progress' },
	{ tr: 'ilgi', en: 'interest' },
	{ tr: 'ilgili', en: 'related' },
	{ tr: 'ilk', en: 'first' },
	{ tr: 'ilk yardım', en: 'first aid' },
	{ tr: 'ilke', en: 'principle' },
	{ tr: 'imkan', en: 'possibility' },
	{ tr: 'incelemek', en: 'to examine' },
	{ tr: 'indirim', en: 'discount' },
	{ tr: 'ingilizce', en: 'English' },
	{ tr: 'iş adamı', en: 'businessman' },
	{ tr: 'iş görüşmesi', en: 'job interview' },
	{ tr: 'işaret etmek', en: 'to point' },
	{ tr: 'işe almak', en: 'to hire' },
	{ tr: 'işitmek', en: 'to hear' },
	{ tr: 'ithal', en: 'imported' },
	{ tr: 'itiraf', en: 'confession' },
	{ tr: 'iyileşmek', en: 'to recover' },
	{ tr: 'izci', en: 'scout' },
	{ tr: 'izlemek', en: 'to watch' },
	{ tr: 'kabuk', en: 'shell' },
	{ tr: 'kabul', en: 'acceptance' },
	{ tr: 'kafein', en: 'caffeine' },
	{ tr: 'kahvaltı', en: 'breakfast' },
	{ tr: 'kakao', en: 'cocoa' },
	{ tr: 'kalabalık', en: 'crowded' },
	{ tr: 'kalıcı', en: 'permanent' },
	{ tr: 'kalp krizi', en: 'heart attack' },
	{ tr: 'kampanya', en: 'campaign' },
	{ tr: 'kanal', en: 'channel' },
	{ tr: 'kanser', en: 'cancer' },
	{ tr: 'kapasite', en: 'capacity' },
	{ tr: 'kapatmak', en: 'to close' },
	{ tr: 'kapı zili', en: 'doorbell' },
	{ tr: 'karar', en: 'decision' },
	{ tr: 'karşılaştırmak', en: 'to compare' },
	{ tr: 'karşılık', en: 'in return' },
	{ tr: 'kasap', en: 'butcher' },
	{ tr: 'kaset', en: 'cassette' },
	{ tr: 'kazak', en: 'sweater' },
	{ tr: 'kelebek', en: 'butterfly' },
	{ tr: 'kemer', en: 'belt' },
	{ tr: 'kısa yol', en: 'shortcut' },
	{ tr: 'kıyı', en: 'shore' },
	{ tr: 'kilo vermek', en: 'to lose weight' },
	{ tr: 'kimya', en: 'chemistry' },
	{ tr: 'kira ödemek', en: 'to pay rent' },
	{ tr: 'kişi', en: 'person' },
	{ tr: 'kişisel', en: 'personal' },
	{ tr: 'kitapçı', en: 'bookseller' },
	{ tr: 'kivi', en: 'kiwi' },
	{ tr: 'klima', en: 'air conditioning' },
	{ tr: 'komik', en: 'funny' },
	{ tr: 'konferans salonu', en: 'conference room' },
	{ tr: 'konfor', en: 'comfort' },
	{ tr: 'konser', en: 'concert' },
	{ tr: 'kontrol', en: 'control' },
	{ tr: 'kopya', en: 'copy' },
	{ tr: 'korumak', en: 'to protect' },
	{ tr: 'koşul', en: 'condition' },
	{ tr: 'koy', en: 'bay' },
	{ tr: 'kredi', en: 'credit' },
	{ tr: 'kredi kartı', en: 'credit card' },
	{ tr: 'kritik', en: 'critical' },
	{ tr: 'kural', en: 'rule' },
	{ tr: 'kurban', en: 'sacrifice' },
	{ tr: 'kusur', en: 'fault' },
	{ tr: 'külah', en: 'cone' },
	{ tr: 'kütüphane', en: 'library' },
	{ tr: 'leke', en: 'stain' },
	{ tr: 'liman', en: 'port' },
	{ tr: 'limon', en: 'lemon' },
	{ tr: 'lokum', en: 'Turkish delight' },
	{ tr: 'maalesef', en: 'unfortunately' },
	{ tr: 'madde', en: 'substance' },
	{ tr: 'mahalle', en: 'neighborhood' },
	{ tr: 'makas', en: 'scissors' },
	{ tr: 'makyaj', en: 'makeup' },
	{ tr: 'maliyet', en: 'cost' },
	{ tr: 'marul', en: 'lettuce' },
	{ tr: 'masa örtüsü', en: 'tablecloth' },
	{ tr: 'matematik', en: 'mathematics' },
	{ tr: 'mayıs', en: 'May' },
	{ tr: 'mayo', en: 'swimsuit' },
	{ tr: 'mekan', en: 'place' },
	{ tr: 'merdiven', en: 'stairs' },
	{ tr: 'meslek', en: 'profession' },
	{ tr: 'metal', en: 'metal' },
	{ tr: 'mısır', en: 'corn' },
	{ tr: 'mühendis', en: 'engineer' },
	{ tr: 'mükemmel', en: 'perfect' },
	{ tr: 'müşteri hizmetleri', en: 'customer service' },
	{ tr: 'nakliyat', en: 'transport' },
	{ tr: 'narenciye', en: 'citrus' },
	{ tr: 'nereye', en: 'where to' },
	{ tr: 'nisan', en: 'April' },
	{ tr: 'nişanlı', en: 'engaged' },
	{ tr: 'not', en: 'note' },
	{ tr: 'oda numarası', en: 'room number' },
	{ tr: 'ödünç almak', en: 'to borrow' },
	{ tr: 'ölçmek', en: 'to measure' },
	{ tr: 'ölüm', en: 'death' },
	{ tr: 'önceden', en: 'in advance' },
	{ tr: 'örgüt', en: 'organization' },
	{ tr: 'özür', en: 'apology' },
	{ tr: 'özür dilemek', en: 'to apologize' },
	{ tr: 'pansiyon', en: 'guesthouse' },
	{ tr: 'peşin', en: 'cash' },
	{ tr: 'pırasa', en: 'leek' },
	{ tr: 'pil', en: 'battery' },
	{ tr: 'pizza', en: 'pizza' },
	{ tr: 'polis merkezi', en: 'police station' },
	{ tr: 'portakal suyu', en: 'orange juice' },
	{ tr: 'posta kodu', en: 'postal code' },
	{ tr: 'rahatsız', en: 'uncomfortable' },
	{ tr: 'rapor', en: 'report' },
	{ tr: 'rehber', en: 'guide' },
	{ tr: 'resmi', en: 'formal' },
	{ tr: 'sabah kahvaltısı', en: 'breakfast' },
	{ tr: 'sabır', en: 'patience' },
	{ tr: 'sahip', en: 'owner' },
	{ tr: 'sanayi', en: 'industry' },
	{ tr: 'satranç', en: 'chess' },
	{ tr: 'satış elemanı', en: 'salesperson' },
	{ tr: 'söylemek', en: 'to say' },
	{ tr: 'şarap', en: 'wine' },
	{ tr: 'şüphe', en: 'doubt' },
	{ tr: 'tablo', en: 'painting' },
	{ tr: 'tadilat', en: 'renovation' },
	{ tr: 'tahıl', en: 'grain' },
	{ tr: 'tahmin etmek', en: 'to guess' },
	{ tr: 'takı', en: 'jewelry' },
	{ tr: 'taksit', en: 'installment' },
	{ tr: 'tam', en: 'full' },
	{ tr: 'tanık', en: 'witness' },
	{ tr: 'taraftar', en: 'fan' },
	{ tr: 'taraf', en: 'side' },
	{ tr: 'tasarım', en: 'design' },
	{ tr: 'taşınmak', en: 'to move' },
	{ tr: 'taze', en: 'fresh' },
	{ tr: 'tebrik kartı', en: 'greeting card' },
	{ tr: 'teklif', en: 'offer' },
	{ tr: 'tekstil', en: 'textile' },
	{ tr: 'telefon rehberi', en: 'phone book' },
	{ tr: 'temel', en: 'basic' },
	{ tr: 'tercih etmek', en: 'to prefer' },
	{ tr: 'terk etmek', en: 'to leave' },
	{ tr: 'tesadüf', en: 'coincidence' },
	{ tr: 'teşekkür', en: 'thanks' },
	{ tr: 'tıp', en: 'medicine' },
	{ tr: 'tıraş', en: 'shave' },
	{ tr: 'tohum', en: 'seed' },
	{ tr: 'tur', en: 'tour' },
	{ tr: 'turizm', en: 'tourism' },
	{ tr: 'tutku', en: 'passion' },
	{ tr: 'tuzak', en: 'trap' },
	{ tr: 'tüketim', en: 'consumption' },
	{ tr: 'uçurmak', en: 'to fly' },
	{ tr: 'ulus', en: 'nation' },
	{ tr: 'uyarı', en: 'warning' },
	{ tr: 'uygun fiyat', en: 'reasonable price' },
	{ tr: 'uyku', en: 'sleep' },
	{ tr: 'yapı', en: 'structure' },
	{ tr: 'zemin kat', en: 'ground floor' },
	{ tr: 'zeytinyağı', en: 'olive oil' },
	{ tr: 'acele', en: 'hurry' },
	{ tr: 'açı', en: 'angle' },
	{ tr: 'açık hava', en: 'outdoors' },
	{ tr: 'açıklama', en: 'explanation' },
	{ tr: 'adet', en: 'piece' },
	{ tr: 'adil', en: 'fair' },
	{ tr: 'ağ', en: 'network' },
	{ tr: 'ağrı kesici', en: 'painkiller' },
	{ tr: 'akıcı', en: 'fluent' },
	{ tr: 'akış', en: 'flow' },
	{ tr: 'akrep', en: 'scorpion' },
	{ tr: 'aksamak', en: 'to limp' },
	{ tr: 'aktif', en: 'active' },
	{ tr: 'alan', en: 'area' },
	{ tr: 'alışmak', en: 'to get used to' },
	{ tr: 'ambulans', en: 'ambulance' },
	{ tr: 'antrenman', en: 'training' },
	{ tr: 'araç', en: 'vehicle' },
	{ tr: 'arka plan', en: 'background' },
	{ tr: 'artı', en: 'plus' },
	{ tr: 'av', en: 'hunt' },
	{ tr: 'ayak bileği', en: 'ankle' },
	{ tr: 'ayıklamak', en: 'to sort' },
	{ tr: 'ayrı', en: 'separate' },
	{ tr: 'azınlık', en: 'minority' },
	{ tr: 'bahçıvan', en: 'gardener' },
	{ tr: 'bakış', en: 'look' },
	{ tr: 'balıkçı', en: 'fisherman' },
	{ tr: 'baskı', en: 'pressure' },
	{ tr: 'başarısız', en: 'unsuccessful' },
	{ tr: 'başlangıç', en: 'beginning' },
	{ tr: 'başvuru', en: 'application' },
	{ tr: 'batmak', en: 'to sink' },
	{ tr: 'bazıları', en: 'some of them' },
	{ tr: 'belirsiz', en: 'uncertain' },
	{ tr: 'beraberinde', en: 'along with' },
	{ tr: 'beyaz eşya', en: 'household appliance' },
	{ tr: 'bırakma', en: 'leaving' },
	{ tr: 'bilinç', en: 'consciousness' },
	{ tr: 'bilinçli', en: 'conscious' },
	{ tr: 'birikim', en: 'savings' },
	{ tr: 'birinci', en: 'first' },
	{ tr: 'biyografi', en: 'biography' },
	{ tr: 'boşanma', en: 'divorce' },
	{ tr: 'boyacı', en: 'painter' },
	{ tr: 'boyut', en: 'dimension' },
	{ tr: 'börek', en: 'pastry' },
	{ tr: 'büyükelçi', en: 'ambassador' },
	{ tr: 'büyüklük', en: 'size' },
	{ tr: 'cazibe', en: 'attraction' },
	{ tr: 'cezaevi', en: 'prison' },
	{ tr: 'ciddi', en: 'serious' },
	{ tr: 'çağrı', en: 'call' },
	{ tr: 'çalı', en: 'bush' },
	{ tr: 'çalışma', en: 'study' },
	{ tr: 'çamaşır makinesi', en: 'washing machine' },
	{ tr: 'çekici', en: 'attractive' },
	{ tr: 'çevre kirliliği', en: 'pollution' },
	{ tr: 'çiftlik', en: 'farm' },
	{ tr: 'dağıtmak', en: 'to distribute' },
	{ tr: 'damla', en: 'drop' },
	{ tr: 'değişiklik', en: 'change' },
	{ tr: 'denge', en: 'balance' },
	{ tr: 'deniz ürünleri', en: 'seafood' },
	{ tr: 'depo', en: 'warehouse' },
	{ tr: 'devam', en: 'continuation' },
	{ tr: 'dinlenme', en: 'rest' },
	{ tr: 'diplomat', en: 'diplomat' },
	{ tr: 'doğa yürüyüşü', en: 'hiking' },
	{ tr: 'dönüşüm', en: 'conversion' },
	{ tr: 'dükkân', en: 'store' },
	{ tr: 'düzenleme', en: 'arrangement' },
	{ tr: 'efekt', en: 'effect' },
	{ tr: 'ekipman', en: 'equipment' },
	{ tr: 'ekonomik', en: 'economic' },
	{ tr: 'elçilik', en: 'embassy' },
	{ tr: 'emekli maaşı', en: 'pension' },
	{ tr: 'emir', en: 'order' },
	{ tr: 'eş', en: 'spouse' },
	{ tr: 'etkinlik', en: 'event' },
	{ tr: 'etkileşim', en: 'interaction' },
	{ tr: 'evcil hayvan', en: 'pet' },
	{ tr: 'farkındalık', en: 'awareness' },
	{ tr: 'geri dönüş', en: 'return' },
	{ tr: 'getiri', en: 'return' },
	{ tr: 'görüş', en: 'opinion' },
	{ tr: 'gösterge', en: 'indicator' },
	{ tr: 'güçlük', en: 'difficulty' },
	{ tr: 'ısınmak', en: 'to warm up' },
	{ tr: 'işe', en: 'to work' },
	{ tr: 'iyileşme', en: 'recovery' },
	{ tr: 'iz', en: 'trace' },
	{ tr: 'karşılaşma', en: 'match' },
	{ tr: 'ödünç', en: 'loan' },
	{ tr: 'terk', en: 'abandonment' },
	{ tr: 'acı biber', en: 'hot pepper' },
	{ tr: 'adım adım', en: 'step by step' },
	{ tr: 'aferin', en: 'well done' },
	{ tr: 'ağırlık', en: 'weight' },
	{ tr: 'akıllı telefon', en: 'smartphone' },
	{ tr: 'alışveriş listesi', en: 'shopping list' },
	{ tr: 'ana dil', en: 'mother tongue' },
	{ tr: 'anahtar kelime', en: 'keyword' },
	{ tr: 'antrenör', en: 'coach' },
	{ tr: 'araba yolculuğu', en: 'road trip' },
	{ tr: 'arka bahçe', en: 'backyard' },
	{ tr: 'asker', en: 'soldier' },
	{ tr: 'atık su', en: 'wastewater' },
	{ tr: 'avrupa birliği', en: 'European Union' },
	{ tr: 'ay çiçeği', en: 'sunflower' },
	{ tr: 'ayaklık', en: 'pedal' },
	{ tr: 'balkon kapısı', en: 'balcony door' },
	{ tr: 'bankacı', en: 'banker' },
	{ tr: 'basketbol', en: 'basketball' },
	{ tr: 'başarı hikayesi', en: 'success story' },
	{ tr: 'başkan', en: 'president' },
	{ tr: 'batılı', en: 'western' },
	{ tr: 'bebek bezi', en: 'diaper' },
	{ tr: 'belgesel', en: 'documentary' },
	{ tr: 'beyin fırtınası', en: 'brainstorming' },
	{ tr: 'bilet fiyatı', en: 'ticket price' },
	{ tr: 'bilgisayar oyunu', en: 'computer game' },
	{ tr: 'bilim kurgu', en: 'science fiction' },
	{ tr: 'bir dahaki sefere', en: 'next time' },
	{ tr: 'bir şey değil', en: 'you\'re welcome' },
	{ tr: 'biraz önce', en: 'a moment ago' },
	{ tr: 'bisiklet yolu', en: 'bike path' },
	{ tr: 'boş zaman', en: 'free time' },
	{ tr: 'bulutlu', en: 'cloudy' },
	{ tr: 'buzdolabı', en: 'refrigerator' },
	{ tr: 'büyükelçilik', en: 'embassy' },
	{ tr: 'çalışma masası', en: 'desk' },
	{ tr: 'çevre dostu', en: 'eco-friendly' },
	{ tr: 'çıkış kapısı', en: 'exit door' },
	{ tr: 'çocuk bakıcısı', en: 'babysitter' },
	{ tr: 'dağ evi', en: 'mountain house' },
	{ tr: 'deniz ürünü', en: 'seafood' },
	{ tr: 'dijital', en: 'digital' },
	{ tr: 'dil kursu', en: 'language course' },
	{ tr: 'doğum kontrolü', en: 'birth control' },
	{ tr: 'dondurma külahı', en: 'ice cream cone' },
	{ tr: 'döviz', en: 'foreign currency' },
	{ tr: 'dünya barışı', en: 'world peace' },
	{ tr: 'düşünce', en: 'thought' },
	{ tr: 'elektrik faturası', en: 'electricity bill' },
	{ tr: 'eş anlamlı', en: 'synonym' },
	{ tr: 'evlilik', en: 'marriage' },
	{ tr: 'fıstık ezmesi', en: 'peanut butter' },
	{ tr: 'gıda güvenliği', en: 'food safety' },
	{ tr: 'gözlük', en: 'glasses' },
	{ tr: 'güneş kremi', en: 'sunscreen' },
	{ tr: 'güneşlenmek', en: 'to sunbathe' },
	{ tr: 'gürültü kirliliği', en: 'noise pollution' },
	{ tr: 'hafta içi', en: 'weekday' },
	{ tr: 'hava durumu', en: 'weather forecast' },
	{ tr: 'hayat sigortası', en: 'life insurance' },
	{ tr: 'hidroelektrik', en: 'hydroelectric' },
	{ tr: 'kablosuz', en: 'wireless' },
	{ tr: 'kahve makinesi', en: 'coffee machine' },
	{ tr: 'kaldırım', en: 'pavement' },
	{ tr: 'kan bağışı', en: 'blood donation' },
	{ tr: 'kar yağışı', en: 'snowfall' },
	{ tr: 'kariyer', en: 'career' },
	{ tr: 'katılım', en: 'participation' },
	{ tr: 'kayınvalide', en: 'mother-in-law' },
	{ tr: 'kısa film', en: 'short film' },
	{ tr: 'kış mevsimi', en: 'winter season' },
	{ tr: 'kolej', en: 'college' },
	{ tr: 'konsolosluk', en: 'consulate' },
	{ tr: 'kültürel', en: 'cultural' },
	{ tr: 'küresel', en: 'global' },
	{ tr: 'masaj', en: 'massage' },
	{ tr: 'medya', en: 'media' },
	{ tr: 'meyve salatası', en: 'fruit salad' },
	{ tr: 'mobil uygulama', en: 'mobile app' },
	{ tr: 'nakliye şirketi', en: 'shipping company' },
	{ tr: 'nüfus', en: 'population' },
	{ tr: 'ödeme yöntemi', en: 'payment method' },
	{ tr: 'öğretim üyesi', en: 'faculty member' },
	{ tr: 'ölüm cezası', en: 'death penalty' },
	{ tr: 'önem vermek', en: 'to care about' },
	{ tr: 'örnek cümle', en: 'example sentence' },
	{ tr: 'öz farkındalık', en: 'self-awareness' },
	{ tr: 'pasaport kontrolü', en: 'passport control' },
	{ tr: 'patlıcan', en: 'eggplant' },
	{ tr: 'pilotaj', en: 'piloting' },
	{ tr: 'reçete', en: 'prescription' },
	{ tr: 'sağlık sigortası', en: 'health insurance' },
	{ tr: 'sanal', en: 'virtual' },
	{ tr: 'sertifika', en: 'certificate' },
	{ tr: 'sosyal medya', en: 'social media' },
	{ tr: 'sürdürülebilir', en: 'sustainable' },
	{ tr: 'şeffaf', en: 'transparent' },
	{ tr: 'şeker hastalığı', en: 'diabetes' },
	{ tr: 'tahsilat', en: 'collection' },
	{ tr: 'tasarruf hesabı', en: 'savings account' },
	{ tr: 'tatil köyü', en: 'holiday village' },
	{ tr: 'tekerlekli sandalye', en: 'wheelchair' },
	{ tr: 'telefon numarası', en: 'phone number' },
	{ tr: 'trafik ışığı', en: 'traffic light' },
	{ tr: 'uluslararası', en: 'international' },
	{ tr: 'uydu', en: 'satellite' },
	{ tr: 'ücretsiz', en: 'free of charge' },
	{ tr: 'veteriner', en: 'veterinarian' },
	{ tr: 'video konferans', en: 'video conference' },
	{ tr: 'yaban mersini', en: 'blueberry' },
	{ tr: 'yasal uyarı', en: 'legal notice' },
	{ tr: 'yazılım', en: 'software' },
	{ tr: 'yemek tarifi', en: 'recipe' },
	{ tr: 'yıldırım', en: 'lightning' },
	{ tr: 'yoğurt', en: 'yogurt' },
	{ tr: 'yol haritası', en: 'roadmap' },
	{ tr: 'yüzme havuzu', en: 'swimming pool' },
	{ tr: 'zaman çizelgesi', en: 'timeline' },
	{ tr: 'ayakkabı boyutu', en: 'shoe size' },
	{ tr: 'banka hesabı', en: 'bank account' },
	{ tr: 'başvuru formu', en: 'application form' },
	{ tr: 'emeklilik', en: 'retirement' },
	{ tr: 'ihtiyaç', en: 'need' },
	{ tr: 'kaldırım taşı', en: 'paving stone' },
	{ tr: 'kayıt', en: 'registration' },
	{ tr: 'kitapçık', en: 'brochure' },
	{ tr: 'kullanım', en: 'usage' },
	{ tr: 'küçük harf', en: 'lowercase' },
	{ tr: 'para birimi', en: 'currency' },
	{ tr: 'performans', en: 'performance' },
	{ tr: 'sağlık', en: 'health' },
	{ tr: 'sistem', en: 'system' },
	{ tr: 'şart', en: 'condition' },
	{ tr: 'tema', en: 'theme' },
	{ tr: 'uygulama formu', en: 'application form' },
	{ tr: 'ücret', en: 'fee' },
	{ tr: 'vize', en: 'visa' },
	{ tr: 'yayın', en: 'publication' },
	{ tr: 'yönetim', en: 'management' },
	{ tr: 'zaman dilimi', en: 'time zone' },
];
