export const words = [
  "Ocak|January",
  "Şubat|February",
  "Mart|March",
  "Nissan|April",
  "Mayis|May",
  "Haziran|June",
  "Temuz|July",
  "Ağustos|August",
  "Eylül|September",
  "Ekim|October",
  "Kasım|November",
  "Aralık|December",
  "İlkbahar|Spring",
  "Yaz|Summer",
  "Sonbahar|Fall",
  "Kış|Winter",
  "gelmek|to come",
  "gitmek|to go",
  "yapmak|to do",
  "yemek|to eat",
  "içmek|to drink",
  "konuşmak|to speak",
  "anlamak|to understand",
  "okumak|to read",
  "yazmak|to write",
  "dinlemek|to listen",
  "izlemek|to watch",
  "çalışmak|to work",
  "öğrenmek|to learn",
  "öğretmek|to teach",
  "almak|to take",
  "vermek|to give",
  "sevmek|to love",
  "istemek|to want",
  "bulmak|to find",
  "koymak|to put",
  "söylemek|to say",
  "çağırmak|to call",
  "görmek|to see",
  "duymak|to hear",
  "koklamak|to smell",
  "tatmak|to taste",
  "dokunmak|to touch",
  "kapatmak|to close",
  "açmak|to open",
  "beklemek|to wait",
  "koşmak|to run",
  "yürümek|to walk",
  "oturmak|to sit",
  "kalkmak|to stand up",
  "düşmek|to fall",
  "uyumak|to sleep",
  "uyanmak|to wake up",
  "gülmek|to laugh",
  "ağlamak|to cry",
  "bilmek|to know",
  "anlatmak|to explain",
  "gezmek|to travel",
  "yaşamak|to live",
  "ölmek|to die",
  "kazanmak|to win",
  "kaybetmek|to lose",
  "hatırlamak|to remember",
  "unutmak|to forget",
  "korkmak|to fear",
  "sevinmek|to be happy",
  "üzülmek|to be sad",
  "başlamak|to start",
  "bitirmek|to finish",
  "çizmek|to draw",
  "boyamak|to paint",
  "yüzmek|to swim",
  "atlamak|to jump",
  "kavga etmek|to fight",
  "sarılmak|to hug",
  "öpüşmek|to kiss",
  "tanışmak|to meet",
  "karşılamak|to welcome",
  "uğurlamak|to send off",
  "görüşmek|to see each other",
  "yardım etmek|to help",
  "terk etmek|to leave",
  "dönmek|to return",
  "alışveriş yapmak|to shop",
  "dolaşmak|to wander",
  "denemek|to try",
  "tekrar etmek|to repeat",
  "sormak|to ask",
  "cevaplamak|to answer",
  "taşımak|to carry",
  "göndermek|to send",
  "kullanmak|to use",
  "sürmek|to drive",
  "uçmak|to fly",
  "yıkamak|to wash",
  "temizlemek|to clean",
  "yapıştırmak|to stick",
  "çıkarmak|to remove",
  "çözmek|to solve",
  "geçmek|to pass",
  "kalmak|to stay",
  "ağrımak|to hurt",
  "oynamak|to play",
  "düşünmek|to think",
  "saymak|to count",
  "işaret etmek|to point",
  "ihtiyaç duymak|to need",
  "hissetmek|to feel",
  "yakalamak|to catch",
  "bırakmak|to let go",
  "çekmek|to pull",
  "itmek|to push",
  "dönmek|to turn",
  "ayrılmak|to separate",
  "birleştirmek|to unite",
  "dolaşmak|to stroll",
  "alışmak|to get used to",
  "kabul etmek|to accept",
  "reddetmek|to refuse",
  "takip etmek|to follow",
  "saklamak|to hide",
  "bulunmak|to be located",
  "katılmak|to join",
  "tartışmak|to discuss",
  "paylaşmak|to share",
  "izah etmek|to explain",
  "karar vermek|to decide",
  "korkutmak|to scare",
  "sakinleşmek|to calm down",
  "tavsiye etmek|to recommend",
  "davet etmek|to invite",
  "anlatmak|to tell",
  "sürdürmek|to continue",
  "boşaltmak|to empty",
  "doldurmak|to fill",
  "yakmak|to light",
  "söndürmek|to extinguish",
  "seçmek|to choose",
  "tahmin etmek|to guess",
  "olmak|to be",
  "var olmak|to exist",
  "ihtiyaç duymak|to require",
  "inanmak|to believe",
  "teşekkür etmek|to thank",
  "dilemek|to wish",
  "umut etmek|to hope",
  "başarmak|to achieve",
  "ilgi göstermek|to show interest",
  "övmek|to praise",
  "eleştirmek|to criticize",
  "çalışmak|to study",
  "denemek|to attempt",
  "anlamak|to comprehend",
  "kesmek|to cut",
  "pişirmek|to cook",
  "ısıtmak|to heat",
  "soğutmak|to cool",
  "eklemek|to add",
  "çıkarmak|to subtract",
  "çarpma yapmak|to multiply",
  "bölmek|to divide",
  "beklemek|to expect",
  "aramak|to search",
  "satın almak|to buy",
  "satmak|to sell",
  "istemek|to request",
  "emretmek|to command",
  "emir vermek|to order",
  "şarkı söylemek|to sing",
  "dans etmek|to dance",
  "bahsetmek|to mention",
  "davranmak|to behave",
  "affetmek|to forgive",
  "bağışlamak|to pardon",
  "iyileşmek|to recover",
  "iyileştirmek|to heal",
  "öğretmek|to educate",
  "egzersiz yapmak|to exercise",
  "çalıştırmak|to operate",
  "uygulamak|to apply",
  "tecrübeli olmak|to experience",
  "katılmak|to attend",
  "katılmak|to participate",
  "kaçmak|to escape",
  "yakalamak|to capture",
  "hüküm vermek|to judge",
  "zorlamak|to force",
  "etkilemek|to affect",
  "araştırmak|to research",
  "incelemek|to examine",
  "keşfetmek|to discover",
  "araştırmak|to investigate",
  "taramak|to scan",
  "taramak|to browse",
  "teşhis etmek|to diagnose",
  "tekrar etmek|to reiterate",
  "sınav yapmak|to test",
  "denetlemek|to supervise",
  "gözetlemek|to observe",
  "incelemek|to inspect",
  "analiz etmek|to analyze",
  "özetlemek|to summarize",
  "yorumlamak|to interpret",
  "karşılaştırmak|to compare",
  "ele almak|to handle",
  "yönetmek|to manage",
  "işletmek|to operate",
  "tanımlamak|to define",
  "tasvir etmek|to describe",
  "anlamak|to perceive",
  "gözden geçirmek|to review",
  "sonuçlandırmak|to conclude",
  "incelemek|to scrutinize",
  "daha fazla|more",
  "daha az|less",
  "çok|a lot/much/many",
  "az|a little/few",
  "biraz|some/little bit",
  "birkaç|a few",
  "sık sık|often",
  "bazen|sometimes",
  "hiç|never",
  "her zaman|always",
  "genellikle|usually",
  "nadiren|rarely",
  "çoğunlukla|mostly",
  "arada sırada|occasionally",
  "güzel|beautiful",
  "çirkin|ugly",
  "büyük|big",
  "küçük|small",
  "uzun|long/tall",
  "kısa|short",
  "geniş|wide",
  "dar|narrow",
  "iyi|good",
  "kötü|bad",
  "yeni|new",
  "eski|old",
  "pahalı|expensive",
  "ucuz|cheap",
  "zor|difficult",
  "kolay|easy",
  "hızlı|fast",
  "yavaş|slow",
  "ağır|heavy",
  "hafif|light (weight)",
  "sert|hard",
  "yumuşak|soft",
  "soğuk|cold",
  "sıcak|hot",
  "ıslak|wet",
  "kuru|dry",
  "açık|open/light (color)",
  "kapalı|closed",
  "dolu|full",
  "boş|empty",
  "genç|young",
  "yaşlı|old (age)",
  "zengin|rich",
  "fakir|poor",
  "temiz|clean",
  "kirli|dirty",
  "mutlu|happy",
  "üzgün|sad",
  "sağlıklı|healthy",
  "hasta|sick",
  "güçlü|strong",
  "zayıf|weak",
  "yoksul|needy",
  "şişman|fat",
  "zayıf|thin",
  "kibar|polite",
  "kaba|rude",
  "tembel|lazy",
  "çalışkan|hardworking",
  "sevimli|cute",
  "sevimsiz|unpleasant",
  "akıllı|smart",
  "aptal|stupid",
  "cesur|brave",
  "korkak|coward",
  "taze|fresh",
  "bayat|stale",
  "meşgul|busy",
  "boş|free",
  "kalabalık|crowded",
  "tenha|deserted",
  "parlak|bright",
  "donuk|dull",
  "heyecanlı|excited",
  "sakin|calm",
  "güvenli|safe",
  "tehlikeli|dangerous",
  "değerli|valuable",
  "sağlam|solid",
  "kırılgan|fragile",
  "karlı|snowy",
  "güneşli|sunny",
  "yağmurlu|rainy",
  "bulutlu|cloudy",
  "rüzgarlı|windy",
  "nemli|humid",
  "hoş|pleasant",
  "hoş olmayan|unpleasant",
  "aç|hungry",
  "tok|full (not hungry)",
  "mükemmel|perfect",
  "berbat|terrible",
  "yoğun|intense",
  "hafif|light (intensity)",
  "ciddi|serious",
  "komik|funny",
  "hoş|nice",
  "yaş|wet",
  "karanlık|dark",
  "aydınlık|bright",
  "duygusal|emotional",
  "duygusuz|unemotional",
  "doğal|natural",
  "yapay|artificial",
  "tecrübeli|experienced",
  "tecrübesiz|inexperienced",
  "çılgın|crazy",
  "mantıklı|rational",
  "sinirli|angry",
  "rahat|relaxed",
  "yorgun|tired",
  "enerjik|energetic",
  "katı|strict",
  "esnek|flexible",
  "dikkatli|careful",
  "dikkatsiz|careless",
  "bağımsız|independent",
  "bağımlı|dependent",
  "cömert|generous",
  "cimri|stingy",
  "merhametli|compassionate",
  "merhametsiz|merciless",
  "sabırlı|patient",
  "sabırsız|impatient",
  "tutkulu|passionate",
  "tutkusuz|apathetic",
  "kararlı|determined",
  "kararsız|indecisive",
  "uyumlu|compatible",
  "uyumsuz|incompatible",
  "dost canlısı|friendly",
  "düşmanca|hostile",
  "yenilikçi|innovative",
  "geleneksel|traditional",
  "uygun|appropriate",
  "uygunsuz|inappropriate",
  "düşünceli|thoughtful",
  "düşüncesiz|thoughtless",
  "dürüst|honest",
  "yalancı|liar",
  "mütevazı|modest",
  "kibirli|arrogant",
  "nazik|kind",
  "ürkek|timid",
  "ağırbaşlı|dignified",
  "neşeli|joyful",
  "gamsız|carefree",
  "aceleci|hasty",
  "tedbirli|cautious",
  "görgülü|courteous",
  "görgüsüz|uncultured",
  "Bugünkü toplantı çok önemli.|Today's meeting is very important.",
  "Dünkü hava çok güzeldi.|Yesterday's weather was very beautiful.",
  "Evdeki hesap çarşıya uymaz.|Things don’t always go as planned.",
  "Çantadaki kitap benim.|The book in the bag is mine.",
  "Okuldaki arkadaşlarımı özledim.|I missed my friends at school.",
  "Gördüğümdeki şaşkınlığımı unutamıyorum.|I can’t forget my surprise when I saw it.",
  "Kafedeki müzik çok güzeldi.|The music in the café was very nice.",
  "Annemin yaptığı kek çok lezzetliydi.|The cake my mother made was very delicious.",
  "Yoldaki arabalar çok fazlaydı.|There were a lot of cars on the road.",
  "İşyerindeki arkadaşlarım çok yardımsever.|My colleagues at work are very helpful.",
  "Yüzmeyi çok seviyorum.|I love swimming.",
  "Koşmak sağlıklı bir aktivitedir.|Running is a healthy activity.",
  "Kitap okumak çok faydalıdır.|Reading books is very beneficial.",
  "Yemek pişirmek benim için bir hobi.|Cooking is a hobby for me.",
  "Gezmek için yeni yerler arıyorum.|I am looking for new places for traveling.",
  "Dans etmeyi öğrenmek istiyorum.|I want to learn dancing.",
  "Çalışmak başarıya götürür.|Working leads to success.",
  "Müzik dinlemek beni rahatlatıyor.|Listening to music relaxes me.",
  "Resim yapmak bana keyif veriyor.|Painting gives me joy.",
  "Uyumak için erkenden yatıyorum.|I go to bed early to sleep.",
  "Yazı yazmak benim için terapi gibi.|Writing is like therapy for me.",
  "Balık tutmak sabır gerektirir.|Fishing requires patience.",
  "Dağa tırmanmak çok heyecan verici.|Climbing a mountain is very exciting.",
  "Dikiş dikmek zor bir iştir.|Sewing is a difficult task.",
  "Bahçe işleriyle uğraşmak bana huzur veriyor.|Gardening gives me peace.",
  "Araba kullanmayı yeni öğrendim.|I just learned driving.",
  "Şarkı söylemek yetenek gerektirir.|Singing requires talent.",
  "Film izlemek en sevdiğim aktivitedir.|Watching movies is my favorite activity.",
  "Arkadaşlarla buluşmak bana iyi geliyor.|Meeting with friends does me good.",
  "Bisiklete binmek çok eğlencelidir.|Riding a bike is very fun.",
  "Yeni diller öğrenmek beni mutlu ediyor.|Learning new languages makes me happy.",
  "Fotoğraf çekmek hobilerimden biridir.|Taking photos is one of my hobbies.",
  "Ev temizlemek zorunlu bir iştir.|Cleaning the house is a mandatory task.",
  "Oyun oynamak çocuklar için önemlidir.|Playing games is important for children.",
  "Alışveriş yapmak zaman alıyor.|Shopping takes time.",
  "Piyano çalmak sabır gerektirir.|Playing the piano requires patience.",
  "Yürüyüş yapmak formda kalmak için iyidir.|Taking a walk is good for staying in shape.",
  "Film yapmak yaratıcılık gerektirir.|Making a movie requires creativity.",
  "Sunum yapmak biraz heyecan verici.|Giving a presentation is a bit exciting.",
  "Spor yapmak sağlıklı bir yaşamın parçasıdır.|Exercising is part of a healthy life.",
  "Sen geldiğinden beri her şey değişti.|Everything has changed since you came.",
  "Gitmeden önce bavulunu hazırlamalısın.|You should pack your suitcase before you go.",
  "Geldikten sonra seni arayacağım.|I will call you after I come.",
  "Gitmeden önce bizi arayabilir misin?|Can you call us before you go?",
  "Geldikten sonra birlikte yemek yeriz.|We can eat together after you come.",
  "Sabahdan önce yürüyüş yaparım.|I go for a walk before morning.",
  "Akşamdan sonra kitap okurum.|I read a book after evening.",
  "Saat beşe kadar burada olmalısın.|You should be here until five o’clock.",
  "Sabah ve akşam arasında çalışırım.|I work between morning and evening.",
  "Öğle ve akşam arasında dinlenirim.|I rest between noon and evening.",
  "Gittikten sonra her gün seni düşündüm.|I thought about you every day after you left.",
  "Sen geldiğinden beri kendimi daha iyi hissediyorum.|I have been feeling better since you came.",
  "Yemek yemeden önce ellerimi yıkarım.|I wash my hands before eating.",
  "Yemek yedikten sonra dişlerimi fırçalarım.|I brush my teeth after eating.",
  "Seninle konuştuktan sonra karar verdim.|I made a decision after talking to you.",
  "Başlamadan önce plan yapmalıyız.|We should make a plan before starting.",
  "Başladıktan sonra durmak istemedim.|I didn’t want to stop after starting.",
  "İşten önce kahve içerim.|I drink coffee before work.",
  "İşten sonra yürüyüş yaparım.|I go for a walk after work.",
  "Doğumdan önce her şey hazırdı.|Everything was ready before birth.",
  "Doğumdan sonra hayatımız değişti.|Our lives changed after birth.",
  "Uyanır uyanmaz kahve içtim.|I drank coffee right after waking up.",
  "Uyumadan önce kitap okurum.|I read a book before sleeping.",
  "Akşamdan önce seni arayacağım.|I will call you before evening.",
  "Akşamdan sonra sinemaya gideceğiz.|We will go to the cinema after evening.",
  "Okuldan önce ödevimi yaparım.|I do my homework before school.",
  "Okuldan sonra arkadaşlarımla buluşurum.|I meet my friends after school.",
  "Mezun olduktan sonra iş aramaya başladım.|I started looking for a job after graduation.",
  "Sınavdan önce çok çalıştım.|I studied a lot before the exam.",
  "Sınavdan sonra rahatladım.|I relaxed after the exam.",
  "0|sıfır",
  "1|bir",
  "2|iki",
  "3|üç",
  "4|dört",
  "5|beş",
  "6|altı",
  "7|yedi",
  "8|sekiz",
  "9|dokuz",
  "10|on",
  "20|yirmi",
  "23|yirmi üç",
  "30|otuz",
  "39|otuz dokuz",
  "40|kırk",
  "44|kırk dört",
  "50|elli",
  "58|elli sekiz",
  "60|altmış",
  "65|altmış beş",
  "70|yetmiş",
  "72|yetmiş iki",
  "80|seksen",
  "87|seksen yedi",
  "90|doksan",
  "96|doksan altı",
  "100|yüz",
  "araba|car",
  "ev|house",
  "okul|school",
  "masa|table",
  "sandalye|chair",
  "kitap|book",
  "defter|notebook",
  "kalem|pen",
  "bilgisayar|computer",
  "telefon|phone",
  "bahçe|garden",
  "şehir|city",
  "köy|village",
  "sokak|street",
  "park|park",
  "dağ|mountain",
  "deniz|sea",
  "göl|lake",
  "nehir|river",
  "orman|forest",
  "çöl|desert",
  "hava|air",
  "su|water",
  "ateş|fire",
  "toprak|soil",
  "ağaç|tree",
  "çiçek|flower",
  "yaprak|leaf",
  "meyve|fruit",
  "sebze|vegetable",
  "elma|apple",
  "armut|pear",
  "muz|banana",
  "portakal|orange",
  "üzüm|grape",
  "çilek|strawberry",
  "karpuz|watermelon",
  "kavun|melon",
  "domates|tomato",
  "salatalık|cucumber",
  "biber|pepper",
  "patates|potato",
  "havuç|carrot",
  "soğan|onion",
  "sarımsak|garlic",
  "ekmek|bread",
  "süt|milk",
  "peynir|cheese",
  "yoğurt|yogurt",
  "et|meat",
  "balık|fish",
  "tavuk|chicken",
  "yumurta|egg",
  "pirinç|rice",
  "makarna|pasta",
  "çorba|soup",
  "salata|salad",
  "kahve|coffee",
  "çay|tea",
  "şeker|sugar",
  "tuz|salt",
  "yağ|oil",
  "tereyağı|butter",
  "bal|honey",
  "reçel|jam",
  "çikolata|chocolate",
  "dondurma|ice cream",
  "tatlı|dessert",
  "pasta|cake",
  "kurabiye|cookie",
  "bisküvi|biscuit",
  "meyve suyu|fruit juice",
  "gazoz|soda",
  "bardak|glass",
  "şişe|bottle",
  "kupa|cup",
  "tabak|plate",
  "çatal|fork",
  "kaşık|spoon",
  "bıçak|knife",
  "tepsi|tray",
  "tencere|pot",
  "tava|pan",
  "kap|container",
  "çamaşır makinesi|washing machine",
  "bulaşık makinesi|dishwasher",
  "buzdolabı|refrigerator",
  "fırın|oven",
  "mikrodalga|microwave",
  "klima|air conditioner",
  "ısıtıcı|heater",
  "elektrik|electricity",
  "şarj aleti|charger",
  "pil|battery",
  "kablo|cable",
  "lamba|lamp",
  "ampul|bulb",
  "televizyon|television",
  "radyo|radio",
  "hoparlör|speaker",
  "kulaklık|headphones",
  "kamera|camera",
  "fotoğraf makinesi|photo camera",
  "video kamera|video camera",
  "saat|clock",
  "takvim|calendar",
  "harita|map",
  "ayna|mirror",
  "kapı|door",
  "pencere|window",
  "perde|curtain",
  "halı|carpet",
  "yatak|bed",
  "yastık|pillow",
  "battaniye|blanket",
  "dolap|wardrobe",
  "çekmece|drawer",
  "raf|shelf",
  "kanepe|sofa",
  "koltuk|armchair",
  "tuvalet|toilet",
  "banyo|bathroom",
  "duş|shower",
  "küvet|bathtub",
  "lavabo|sink",
  "sabun|soap",
  "havlu|towel",
  "diş fırçası|toothbrush",
  "diş macunu|toothpaste",
  "tıraş bıçağı|razor",
  "şampuan|shampoo",
  "saç kremi|conditioner",
  "saç kurutma makinesi|hair dryer",
  "fırça|brush",
  "tarak|comb",
  "makyaj|makeup",
  "parfüm|perfume",
  "deodorant|deodorant",
  "aile|family",
  "anne|mother",
  "baba|father",
  "kardeş|sibling",
  "abi|older brother",
  "abla|older sister",
  "erkek kardeş|brother",
  "kız kardeş|sister",
  "çocuk|child",
  "bebek|baby",
  "arkadaş|friend",
  "dost|close friend",
  "komşu|neighbor",
  "öğrenci|student",
  "öğretmen|teacher",
  "doktor|doctor",
  "hemşire|nurse",
  "mühendis|engineer",
  "mimar|architect",
  "işçi|worker",
  "çiftçi|farmer",
  "polis|police officer",
  "asker|soldier",
  "avukat|lawyer",
  "hakim|judge",
  "şoför|driver",
  "pilot|pilot",
  "kaptan|captain",
  "garson|waiter",
  "aşçı|chef",
  "temizlikçi|cleaner",
  "bahçıvan|gardener",
  "tesisatçı|plumber",
  "elektrikçi|electrician",
  "kuaför|hairdresser",
  "terzi|tailor",
  "satıcı|seller",
  "müşteri|customer",
  "yazar|writer",
  "şair|poet",
  "sanatçı|artist",
  "müzisyen|musician",
  "şarkıcı|singer",
  "dansçı|dancer",
  "oyuncu|actor",
  "yönetmen|director",
  "prodüktör|producer",
  "babamın babası|my father's father (grandfather)",
  "annemin babası|my mother's father (grandfather)",
  "babamın annesi|my father's mother (grandmother)",
  "annemin annesi|my mother's mother (grandmother)",
  "babamın erkek kardeşi|my father's brother (uncle, amca)",
  "babamın kız kardeşi|my father's sister (aunt, hala)",
  "annemin erkek kardeşi|my mother's brother (uncle, dayı)",
  "annemin kız kardeşi|my mother's sister (aunt, teyze)",
  "erkek kardeşim|my brother",
  "kız kardeşim|my sister",
  "amca|uncle (father's brother)",
  "dayı|uncle (mother's brother)",
  "hala|aunt (father's sister)",
  "teyze|aunt (mother's sister)",
  "kuzen|cousin",
  "yeğen|niece/nephew",
  "kayınpeder|father-in-law",
  "kayınvalide|mother-in-law",
  "enişte|brother-in-law",
  "yenge|sister-in-law",
  "dede|grandfather",
  "nine|grandmother",
  "torun|grandchild",
  "oğul|son",
  "kız evlat|daughter",
  "karı|wife",
  "koca|husband",
  "eş|spouse",
  "üvey anne|stepmother",
  "üvey baba|stepfather",
  "üvey kardeş|step sibling",
  "üvey oğul|stepson",
  "üvey kız|stepdaughter",
  "evlat|offspring",
  "evlatlık|adopted child",
  "torun oğul|grandson",
  "torun kız|granddaughter",
  "ikiz|twin",
  "üçüz|triplet",
  "akraba|relative",
  "kuzenin çocuğu|cousin’s child",
  "yetişkin|adult",
  "genç|youth",
  "çift|couple",
  "ağaç yaşken eğilir|you can’t teach an old dog new tricks",
  "ak akçe kara gün içindir|save for a rainy day",
  "akıl akıldan üstündür|two heads are better than one",
  "ateş düştüğü yeri yakar|the fire burns where it falls",
  "ayağını yorganına göre uzat|cut your coat according to your cloth",
  "balık baştan kokar|a fish rots from the head down",
  "başa gelen çekilir|what is done cannot be undone",
  "bıçak kemiğe dayanmak|to be fed up",
  "bugünün işini yarına bırakma|don’t put off till tomorrow what you can do today",
  "damlaya damlaya göl olur|many a little makes a mickle",
  "deliye her gün bayram|every day is a holiday for the mad",
  "dereyi görmeden paçayı sıvamak|don’t count your chickens before they hatch",
  "dişe diş, göze göz|an eye for an eye, a tooth for a tooth",
  "dost kara günde belli olur|a friend in need is a friend indeed",
  "düşenin dostu olmaz|a fallen person has no friends",
  "el elden üstündür|there is always someone better",
  "el elin eşeğini türkü çağırarak arar|no one will care about your problem as much as you do",
  "el elin yerini doldurmaz|one hand does not fill another’s place",
  "elbette her yiğidin yoğurt yiyişi farklıdır|to each his own",
  "etekleri zil çalmak|to be over the moon",
  "evdeki hesap çarşıya uymaz|things don’t always go as planned",
  "fırsat bu fırsat|make hay while the sun shines",
  "göz var nizam var|everything in its place",
  "gülü seven dikenine katlanır|every rose has its thorn",
  "gün doğmadan neler doğar|anything can happen",
  "gözden ırak olan gönülden de ırak olur|out of sight, out of mind",
  "göz var nizam var|there is order in the universe",
  "hatasız kul olmaz|nobody is perfect",
  "havlayan köpek ısırmaz|a barking dog never bites",
  "her işte bir hayır vardır|every cloud has a silver lining",
  "her yiğidin bir yoğurt yiyişi vardır|each to their own",
  "iki dirhem bir çekirdek|to be well-dressed",
  "işleyen demir pas tutmaz|a rolling stone gathers no moss",
  "kan kusup kızılcık şerbeti içmek|to suffer in silence",
  "kervan yolda düzülür|we’ll cross that bridge when we come to it",
  "kısmetse olur|if it’s meant to be, it will be",
  "mart kapıdan baktırır, kazma kürek yaktırır|March brings cold weather",
  "ne ekersen onu biçersin|you reap what you sow",
  "ok yaydan çıktı|the die is cast",
  "sabır acıdır, meyvesi tatlıdır|patience is bitter, but its fruit is sweet",
  "sakla samanı, gelir zamanı|save the hay for the winter",
  "saman altından su yürütmek|to do something secretly",
  "sinek küçüktür ama mide bulandırır|even a small fly can disturb",
  "sütten ağzı yanan yoğurdu üfleyerek yer|once bitten, twice shy",
  "taşıma su ile değirmen dönmez|you can’t run a mill with carried water",
  "tatlı dil yılanı deliğinden çıkarır|a kind word can get a snake out of its hole",
  "tek taşla duvar olmaz|one stone doesn’t make a wall",
  "vakit nakittir|time is money",
  "yılanın başı küçükken ezilir|nip it in the bud"
];